import {ocrDetail,documentReviewWorkspace,createDocumentReview} from './ocr.js';
import {renderOffice,clearWorkspace} from '/shared/react-ui.js';
import {openBatchUpload} from '/shared/upload-batch.js';
document.body.dataset.workspace='office';
import {api,session,authenticate,logout,download} from '/shared/api.js';
import {createAX} from './ax.js';
import {consultationPending,consultationQuestions,consultationView as renderConsultation,defaultConsultationRequest} from './consultation.js';
import {createAutomationUI} from './automation.js';
import {requestWithdrawn} from '/shared/requests.js';
import {structuredHtml,officeHtml} from '/shared/structured.js';
import {createLegalTools} from './legal.js';
import {createFilingUI} from './filing.js';
import {esc,money,date,list,label,badge,icon,brand,empty,notify,modal,errorPanel,fields,caseReference,setHtmlPresentation,activityLabel} from '/shared/ui.js';

const state={view:'cases',tab:'overview',cases:[],current:null,registry:null,system:null,legalResults:null,legalQuery:'',legalTarget:'law',query:'',filter:'all',offset:0,total:0,error:null};
setHtmlPresentation(html=>officeHtml(html,state));
const automation=createAutomationUI({getState:()=>state,render,load,openCase,openForm});
const ax=createAX({getState:()=>state,render,load,openCase,openForm,pipelineView:()=>automation.pipeline(),openDocumentReview:id=>documentReview.open(id),onCaseUnavailable:id=>{clearUnavailableCase(id);render();}});
const documentReview=createDocumentReview({getState:()=>state,load,formatValue:ax.factorValue,formatContext:ax.factorContext,formatLocation:ax.factorLocation});
const legalTools=createLegalTools({getState:()=>state,render,load,openForm});
const filing=createFilingUI({getState:()=>state,render,load,openForm});
const tabs=[['overview','사건 개요'],['consultation','상담 기록'],['verify','자료 검증'],['issues','법률 쟁점'],['calculate','법률 계산'],['court_forms','법원 서식'],['bundles','문서·결과'],['corrections','보정 대응'],['messages','고객 연락']];
const roles={staff:'사건 담당 직원',lawyer:'담당 변호사',admin:'운영 관리자'};
const legal=()=>session.user?.role==='lawyer';
const cpath=(suffix='')=>`/cases/${encodeURIComponent(state.current.id)}${suffix}`;
const docName=(id)=>state.current?.documents?.find(d=>d.id===id)?.filename||id;
const evidenceText=(ids)=>list(ids).map(id=>esc(docName(id))).join(', ')||'연결된 증거 없음';
const status=(x)=>x.stale?'stale':x.status;
const statusBadge=(x)=>badge(status(x),({decided:'판단 완료',review_required:'재검토 필요',review_approved:'검토 승인',fulfilled:'충족',requested:'자료 요청',unknown:'미확인',reviewed:'검토 완료'})[status(x)]);
function go(view,tab){state.view=view;if(tab)state.tab=tab;state.error=null;render();window.scrollTo(0,0);}
async function ready(){ await load(); await Promise.all([ax.init(),legalTools.init()]); const query=new URLSearchParams(location.search); if(query.get('case')&&!state.current){const tab=tabs.some(([id])=>id===query.get('tab'))?query.get('tab'):'overview';await openCase(query.get('case'),tab);}else render(); }
function clearUnavailableCase(id){const listed=state.cases.some(row=>row.id===id);state.cases=state.cases.filter(row=>row.id!==id);if(listed)state.total=Math.max(0,state.total-1);state.current=null;state.error=null;state.view='cases';state.tab='overview';state.dashboardSelection=null;state.dashboardHistory=null;state.legalResults=null;state.notificationFeed=null;document.querySelector('#dialog')?.close();const url=new URL(location.href);url.searchParams.delete('case');url.searchParams.delete('tab');history.replaceState({},'',url);}
async function load(){try{const [result]=await Promise.all([api(`/cases?limit=25&offset=${state.offset}`),automation.refreshNotifications()]);state.cases=list(result.cases||result);state.total=result.total??state.cases.length;if(state.current)state.current=await api(cpath());state.error=null;}catch(error){if(state.current&&[403,404].includes(error.status))clearUnavailableCase(state.current.id);else state.error=error;}render();}
async function openCase(id,tab='overview'){state.view='case';state.tab=tab;state.error=null;try{state.current=await api('/cases/'+encodeURIComponent(id));render();}catch(error){if([403,404].includes(error.status))clearUnavailableCase(id);else state.error=error;render();}}
async function registry(){if(!state.registry)state.registry=await api('/registry');return state.registry;}
function render(){
  const user=session.user;if(!user)return;
  const names={cases:'사건 목록',case:state.current?.client_name+'님 사건',registry:'법원·발급처',knowledge:'수집 지식함',agent:'AI 검토 작업실',system:'운영 현황'};
  const currentName=names[state.view]||'업무공간';
  renderOffice({state,user,currentName,api,contentHtml:officeHtml(state.error?errorPanel(state.error):view(),state),alarmHtml:automation.alarm(null,true),roleLabel:roles[user.role]||user.role});
  automation.checkAlerts();
}
function nav(id,i,title,count){return `<button class="nav-link ${state.view===id?'active':''}" data-nav="${id}">${icon(i)}${title}${count!=null?`<span class="nav-count">${count}</span>`:''}</button>`;}
function view(){if(state.view==='cases')return casesView();if(state.view==='case')return state.current?caseView():empty('사건을 선택해 주세요','전체 사건에서 진행할 사건을 선택하세요.');if(state.view==='registry')return registryView();if(state.view==='agent')return ax.agentView();if(state.view==='knowledge')return ax.knowledgeView();if(state.view==='system')return systemView();return '';}
function casesView(){
  const cs=state.cases;const pending=cs.reduce((s,c)=>s+(c.blocker_count??list(c.blockers).length),0);const corrections=cs.reduce((s,c)=>s+(c.correction_count??list(c.corrections).filter(x=>x.status!=='approved').length),0);
  const cards=[['전체 담당 사건',state.total,'전체 사건 수','folder'],['확인이 필요한 항목',pending,'현재 목록 · 자료·사실·법률 판단','check'],['보정 대응',corrections,'현재 목록 · 회차별 충족 확인','clock'],['검토 담당',legal()?'변호사':'직원','사건별 권한으로 처리','shield']];
  return `<div class="page-heading"><div><div class="eyebrow">CASE WORKSPACE</div><h1>오늘도, 한 단계 앞으로.</h1><p class="page-subtitle">확인이 필요한 사건과 다음 할 일을 한눈에 살펴보세요.</p></div><button class="button" data-action="new-case">${icon('plus')} 사건 등록</button></div>${ax.dashboard()}<div class="metrics">${cards.map(([title,note,sub,i],n)=>`<div class="metric ${n===1?'attention':''}"><div class="metric-top">${title}${icon(i)}</div><div class="metric-number" ${n===3?'style="font-size:24px;padding:5px 0"':''}>${note}${n<3?'<small>건</small>':''}</div><div class="metric-sub">${sub}</div></div>`).join('')}</div><div class="dashboard-columns"><section class="card"><div class="card-head"><div><div class="overline">MY CASES</div><h2>진행 사건 <span class="muted small">${cs.length}</span></h2></div><button class="icon-button" data-action="refresh" aria-label="사건 새로고침">${icon('refresh')}</button></div><div class="table-toolbar"><label class="search-box">${icon('search')}<input id="case-search" type="search" placeholder="현재 목록에서 이름·사건·법원 검색" aria-label="사건 검색" value="${esc(state.query)}"></label><select id="case-filter" aria-label="진행 단계"><option value="all">모든 단계</option>${[...new Set(cs.map(x=>x.stage))].map(s=>`<option ${state.filter===s?'selected':''}>${esc(s)}</option>`).join('')}</select><span class="spacer"></span><span class="small muted">현재 목록에서 검색</span></div><div id="cases-table">${casesTable()}</div><div class="table-toolbar"><span class="small muted">전체 ${state.total}건 중 ${state.total?state.offset+1:0}–${Math.min(state.offset+25,state.total)}건</span><span class="spacer"></span><button class="button secondary small" data-action="page-prev" ${state.offset===0?'disabled':''}>이전</button><button class="button secondary small" data-action="page-next" ${state.offset+25>=state.total?'disabled':''}>다음</button></div></section><aside><section class="card"><div class="card-head"><h2>다음 할 일</h2><span class="badge orange">확인 필요</span></div><div class="card-body">${cs.length?cs.slice(0,4).map(c=>`<div class="task-row"><div class="task-icon">${icon('clock')}</div><div><strong>${esc(c.next_action||c.blockers?.[0]?.title||'사건 자료와 검토 상태 확인')}</strong><p>${esc(c.client_name)} · ${esc(c.court_name)}</p><p>${c.synthetic?'합성 시연 사건':'담당 '+esc(c.assigned_to||'미지정')}</p></div><button class="icon-button" data-case="${esc(c.id)}" aria-label="${esc(c.client_name)} 사건 열기">${icon('chevron')}</button></div>`).join(''):empty('등록된 사건이 없습니다')}</div></section><div class="agent-card"><div class="agent-icon">${icon('spark')}</div><h3>다음 작업을 함께 정리하세요</h3><p>사건의 부족한 근거와 보정 요구를 검토하고, 담당자가 확인할 보고서를 준비합니다.</p><button class="button secondary small" data-nav="agent">Agent 작업실 ${icon('arrow')}</button></div></aside></div><p class="legal-note">${icon('info')} 합성 시연 사건에는 실제 의뢰인의 개인정보를 사용하지 않습니다.</p>`;
}
function casesTable(){const cs=state.cases.filter(c=>(state.filter==='all'||c.stage===state.filter)&&`${c.client_name} ${c.matter_number||c.engagement_number||''} ${c.id} ${c.court_name}`.toLowerCase().includes(state.query.toLowerCase()));if(!cs.length)return empty('검색 결과가 없습니다','검색어나 진행 단계 조건을 바꿔 주세요.');return `<div class="table-wrap"><table><thead><tr><th>사건 / 의뢰인</th><th>진행 단계</th><th>확인 필요</th><th>최근 변경</th><th></th></tr></thead><tbody>${cs.map(c=>`<tr data-case="${esc(c.id)}" tabindex="0" role="button" aria-label="${esc(c.client_name)} 사건 열기"><td><div class="case-person"><span class="avatar">${esc(c.client_name?.[0]||'사')}</span><div><strong>${esc(c.client_name)}</strong><span class="cell-sub">${esc(c.court_name)} · ${esc(c.id)} ${automation.alarm(c)}</span></div></div></td><td>${badge('pending',c.stage)}</td><td>${(c.blocker_count??list(c.blockers).length)>0?badge('missing',`${c.blocker_count??c.blockers.length}개 항목`):'<span class="muted small">상세 확인</span>'}</td><td class="muted">${date(c.updated_at)}</td><td>${icon('chevron')}</td></tr>`).join('')}</tbody></table></div>`;}
function caseView(){const c=state.current;return `<div class="case-header"><div><div class="eyebrow">${esc(caseReference(c))} ${automation.alarm(c)} ${c.synthetic?'· SYNTHETIC CASE':''}</div><h1>${esc(c.client_name)}님 사건 ${badge('pending',c.stage)}</h1><p class="page-subtitle">${esc(c.court_name)} · ${esc(c.assigned_to||'담당자 미지정')} · 자료 버전 ${c.version}</p></div><div class="row"><button class="button secondary small" data-action="refresh">${icon('refresh')} 새로고침</button><button class="button small" data-action="run-agent" data-kind="case_review">${icon(consultationPending(c)?'message':'spark')} ${consultationPending(c)?'상담 진행':'사건 검토'}</button></div></div><div class="tab-bar" role="tablist">${tabs.map(([id,t])=>`<button class="tab ${state.tab===id?'active':''}" role="tab" aria-selected="${state.tab===id}" data-tab="${id}">${t}</button>`).join('')}</div>${({overview:overview,consultation:consultationView,verify:verifyView,issues:issuesView,calculate:calculateView,court_forms:legalTools.courtFormsView,bundles:bundlesView,corrections:correctionsView,messages:messagesView})[state.tab]?.()||overview()}`;}
function overview(){return `<div data-case-dashboard></div><details class="case-dashboard-history" ${state.dashboardHistory?.caseId===state.current.id&&state.dashboardHistory.open?'open':''}><summary>자동 진행 단계와 처리 이력 <small>자료 확인부터 작성·검토·승인까지</small></summary><div class="cd-history-body">${automation.pipeline()}</div></details>`;}
function actionLabel(action){return ({'document.received':'자료 업로드','document.verified':'원문 대조','fact.confirmed':'사실 확정','issue.decided':'법률 판단','message.created':'고객 메시지','calculation.created':'가정안 계산','request.created':'자료 요청','bundle.created':'검토본 생성','bundle.review_approved':'검토본 승인','correction.created':'보정 요구 등록','correction.reviewed':'보정 답변 검토','correction.approved':'보정 검토 승인','deadline.confirmed':'기한 확정',document_uploaded:'자료 업로드',document_verified:'자료 원문 검증',fact_confirmed:'사실 확정',issue_decided:'법률 쟁점 판단',message_sent:'고객 메시지',request_created:'자료 요청',calculation_created:'가정안 계산',bundle_created:'문서 패키지 생성',bundle_approved:'검토 문서 승인',correction_created:'보정 항목 등록',correction_responded:'보정 답변 검토',correction_approved:'보정 승인'})[action]||activityLabel(action);}
function consultationView(){return renderConsultation(state.current);}
function verifyView(){
  const c=state.current;
  return `${documentReviewWorkspace(c,{requestsHtml:automation.requests(),documentCheck:ax.documentCheck})}
    <details class="card document-secondary-review"><summary>사건 단위로 확정할 사실과 상담 추출 이력</summary><div class="card-body"><section><h2>사실 확정</h2><p class="small muted">여러 서류를 종합해 사건의 값을 확정하는 별도 기록입니다.</p>${list(c.facts).map(f=>`<div class="list-item"><div class="row between"><strong>${esc(f.label)}</strong>${statusBadge(f)}</div><p>${money(f.value)} · 근거: ${evidenceText(f.evidence_ids)}</p>${f.claimed_value!=null?`<p>고객 진술: ${money(f.claimed_value)} · 근거 확인 필요</p>`:''}${f.reason?`<p>${esc(f.reason)}</p>`:''}<button class="button secondary small" data-action="confirm-fact" data-id="${esc(f.id)}">값과 근거 확인</button></div>`).join('')}</section>${ax.extractions(false,'unlinked')}</div></details>
    <button class="button subtle small" data-tab="overview">사건 개요에서 진행 단계와 처리 이력 확인 ${icon('arrow')}</button>`;
}
function issuesView(){return '<div data-case-legal-review></div>';}
function calculateView(){return legalTools.calculateView()+`<details class="section-spacer"><summary>현금흐름 가정 비교</summary>${scenarioView()}</details>`;}
function scenarioView(){const c=state.current;return `<div class="callout warning" style="margin-bottom:20px">${icon('info')}<div><strong>현재 계산은 현금흐름 가정안입니다.</strong><br>아래는 소득·지출 가정을 비교하는 보조 계산입니다. 증빙에 따른 변제계획 계산과 검토 승인은 위 법률 계산에서 진행합니다.</div></div><div class="grid2"><section class="card"><div class="card-head"><h2>현금흐름 비교</h2>${badge('draft','시나리오')}</div><form class="card-body" id="calculate-form"><div class="field-grid">${fields([['income','월 소득 (원)','number',c.facts?.find(f=>f.key==='monthly_income')?.value??'',true],['expenses','월 지출 가정 (원)','number','',true],['months','비교 기간 (개월)','number','36',true],['liquidation_value','청산가치 가정 (원)','number','',true]])}</div><p class="small muted">빈 값은 0원으로 처리하지 않습니다. 가정한 값의 근거를 먼저 확인하세요.</p><div class="form-footer"><button class="button" type="submit">${icon('calc')} 가정안 계산</button></div></form></section><section class="card"><div class="card-head"><h2>계산 이력</h2><span class="small muted">${list(c.calculations).length}개</span></div><div class="card-body">${list(c.calculations).slice().reverse().map(r=>`<div class="list-item"><div class="row between" style="margin-bottom:15px"><strong class="small">${date(r.created_at,true)} · ${esc(r.inputs?.months)}개월</strong>${r.stale?badge('stale'):badge('draft','가정안')}</div><div class="calc-result"><div><span>월 가용 현금</span><strong>${money(r.monthly_available)}</strong></div><div><span>기간 내 합계</span><strong>${money(r.total)}</strong></div><div><span>청산가치 차이</span><strong>${money(r.liquidation_gap)}</strong></div></div>${list(r.warnings).map(w=>`<p class="small muted">${esc(w)}</p>`).join('')}</div>`).join('')||empty('계산한 가정안이 없습니다','입력값을 채워 현금흐름을 비교하세요.')}</div></section></div>`;}
function bundlesView(){const c=state.current;return `${filing.view()}${ax.draftsView()}${automation.outcomes()}<div class="callout neutral" style="margin-bottom:20px">${icon('file')}<div><strong>사건 검증 보고서와 보정 충족표를 하나의 검토본으로 만듭니다.</strong><br>현재 생성물은 검토용 패키지이며, 승인된 법원 제출 서식이 아닙니다. 입력 변경 시 이전 검토 승인은 만료됩니다.</div></div><section class="card"><div class="card-head"><h2>검토 문서 패키지</h2><button class="button" data-action="make-bundle">${icon('plus')} 검토본 생성</button></div><div class="card-body">${list(c.bundles).slice().reverse().map(b=>`<div class="evidence-card"><div class="row between"><div><h3>${esc(b.title)}</h3><p>${date(b.created_at,true)} · 입력 버전 ${b.input_revision}</p></div>${statusBadge(b)}</div><div class="row wrap" style="margin-top:13px">${list(b.documents).map(d=>badge('pending',d)).join('')}</div>${b.stale?`<div class="callout warning" style="margin-top:14px">${icon('info')}${esc(b.stale_reason||'입력 변경으로 다시 생성해야 합니다.')}</div>`:''}<p>${list(b.limitations).map(esc).join(' ')}</p><div class="row wrap" style="margin-top:16px"><button class="button secondary small" data-action="download-bundle" data-id="${esc(b.id)}">${icon('download')} 검토본 다운로드</button>${legal()?`<button class="button small" data-action="approve-bundle" data-id="${esc(b.id)}" ${b.stale?'disabled':''}>검토 승인 기록</button>`:''}</div></div>`).join('')||empty('생성된 문서 패키지가 없습니다','현재 사실·쟁점·보정 요구를 검토용 보고서로 묶을 수 있습니다.')}</div></section>`;}
function correctionsView(){const c=state.current;return `<div class="row between" style="margin-bottom:20px"><div><h2>보정 요구별 충족 확인</h2><p class="small muted" style="margin-top:5px">법원 원문 → 요구 범위 → 증거 → 답변 → 변호사 승인</p></div><div class="row"><button class="button secondary small" data-action="run-agent" data-kind="correction">${icon('spark')} 보정 검토</button><button class="button small" data-action="new-correction">${icon('plus')} 요구 등록</button></div></div><div class="stack">${list(c.corrections).map((r,n)=>`<section class="card"><div class="card-head"><div><div class="issue-number">ROUND ${r.round||1} · ITEM ${String(n+1).padStart(2,'0')}</div><h2>${esc(r.title)}</h2></div>${statusBadge(r)}</div><div class="card-body"><div class="callout neutral"><div><strong>법원 요구</strong><p>${esc(r.requirement)}</p></div></div><dl class="kv" style="margin:20px 0"><dt>원문 근거</dt><dd>${r.source_document_id?esc(docName(r.source_document_id)):'원문 연결 필요'} · ${esc(r.source_page||'—')}쪽</dd><dt>기간·계좌 범위</dt><dd>${esc(r.period||'확인 필요')}</dd><dt>제출 기한</dt><dd>${r.due_date?date(r.due_date):badge('missing','송달 증거 확인 필요')}</dd><dt>연결한 증거</dt><dd>${evidenceText(r.evidence_ids)}</dd></dl>${r.answer?`<div class="issue-section"><h4>검토한 답변</h4><p style="white-space:pre-wrap">${esc(r.answer)}</p></div>`:''}${r.limitations?`<p class="small muted" style="margin-top:12px">${esc(r.limitations)}</p>`:''}<div class="row wrap" style="margin-top:18px"><button class="button secondary small" data-action="respond-correction" data-id="${esc(r.id)}">증거·답변 검토</button>${legal()?`<button class="button small" data-action="approve-correction" data-id="${esc(r.id)}">보정 검토 승인 H-C</button>`:''}</div></div></section>`).join('')||empty('보정 요구가 등록되지 않았습니다','법원 요청을 받으면 원문의 각 요구를 개별 항목으로 등록하세요.')}</div>`;}
function messagesView(){const c=state.current;return `<section class="card"><div class="card-head"><h2>고객과 주고받은 메시지</h2>${badge('pending','고객 포털에 표시')}</div><div class="card-body"><div class="stack" style="max-height:430px;overflow:auto">${list(c.messages).map(m=>`<div class="issue-section"><div class="row between"><strong class="small">${esc(m.sender)} · ${esc(label(m.role))}</strong><time class="small muted">${date(m.created_at,true)}</time></div><p style="white-space:pre-wrap;margin-top:9px">${esc(m.text)}</p></div>`).join('')||empty('주고받은 메시지가 없습니다')}</div><form id="message-form" style="margin-top:23px">${fields([['text','고객에게 전달할 안내','textarea','',true]])}<div class="form-footer"><button type="submit" class="button">${icon('message')} 메시지 보내기</button></div></form></div></section>`;}
function registryView(){const r=state.registry;if(!r)return '<div class="loading"><span class="spinner"></span><p>법원과 공식 발급처를 확인하는 중입니다.</p></div>';return `<div class="page-heading"><div><div class="eyebrow">KOREA · COURTS & DOCUMENTS</div><h1>법원과 서류의 연결</h1><p class="page-subtitle">전국 법원과 정부 서비스의 공식 출처를 확인하고, 사건별 요구를 검토하세요.</p></div></div><div class="callout neutral" style="margin-bottom:22px">${icon('info')}<div>기관 목록과 발급처 안내입니다. 관할 결정·법원별 실무준칙·서식 유효성은 사건의 주소와 신청 시점을 기준으로 별도 확인합니다.</div></div><section class="card" style="margin-bottom:25px"><div class="card-head"><h2>공식 법령·판례 검색</h2><span class="badge gray">국가법령정보센터 연동</span></div><div class="card-body"><form id="legal-search-form" class="row wrap"><label class="field" style="margin:0;min-width:110px"><span>검색 종류</span><select name="target"><option value="law" ${state.legalTarget==='law'?'selected':''}>법령</option><option value="prec" ${state.legalTarget==='prec'?'selected':''}>판례</option></select></label><label class="field" style="margin:0;flex:1;min-width:190px"><span>검색어</span><input name="q" value="${esc(state.legalQuery)}" placeholder="채무자 회생, 개인회생 등" maxlength="200" required></label><button class="button" type="submit" style="align-self:flex-end">${icon('search')} 공식 자료 검색</button></form><div style="margin-top:18px">${legalSearchResults()}</div></div></section><h2 style="margin-bottom:15px">법원별 기본 정보</h2><div class="court-grid">${list(r.courts).map(c=>`<div class="court-card">${icon('building')}<h3>${esc(c.name)}</h3><p>${esc(c.primary_region||c.region||c.jurisdiction||c.notes||c.note||'관할과 적용 기준 확인 필요')}</p>${safeLink(c.official_url||c.url||c.source_urls?.split('\n')[0],'공식 법원 안내')}</div>`).join('')}</div><h2 style="margin:28px 0 15px">서류와 공식 발급처</h2><section class="card"><div class="table-wrap"><table><thead><tr><th>서류</th><th>발급처</th><th>확인할 범위</th><th>발급 안내</th></tr></thead><tbody>${list(r.documents).map(d=>`<tr><td><strong>${esc(d.name)}</strong><span class="cell-sub">${esc(d.category||d.id)}</span></td><td>${esc(d.issuer)}</td><td style="max-width:360px">${esc(d.not_proven||d.purpose||'사건별 필요 기간과 포함 범위를 확인하세요.')}<details style="margin-top:6px"><summary class="small muted">발급 방법</summary><p class="small">${Array.isArray(d.steps)?d.steps.map(esc).join('<br>'):esc(d.steps)}</p></details></td><td>${safeLink(d.issuance_url,'발급처 열기')}</td></tr>`).join('')}</tbody></table></div></section>`;}
function legalSearchResults(){const response=state.legalResults;if(!response)return '<p class="small muted">공식 원문을 검색합니다. 법령의 시행일과 사건 적용 여부는 별도로 검토하세요.</p>';return `${response.message?`<div class="callout ${response.status==='unconfigured'?'warning':'neutral'}">${icon('info')}<div>${esc(response.message)}</div></div>`:''}${list(response.results).map(r=>`<div class="list-item"><strong>${esc(r.title||r.name)}</strong><p>${esc(r.court||r.effective_on||r.date||'원문의 시행일·선고일을 확인하세요.')}</p>${safeLink(r.url,'공식 원문 열기')}</div>`).join('')}${!list(response.results).length&&response.status!=='unconfigured'?'<p class="small muted">검색 결과가 없습니다. 검색어나 연결 상태를 확인하세요.</p>':''}`;}
function safeLink(url,text){try{const u=new URL(url);if(!['https:','http:'].includes(u.protocol))return '<span class="small muted">공식 주소 확인 필요</span>';return `<a class="source-link" href="${esc(u.href)}" target="_blank" rel="noopener noreferrer">${esc(text)} ${icon('arrow')}</a>`;}catch{return '<span class="small muted">공식 주소 확인 필요</span>';}}
function systemView(){
  const s=state.system;if(!s)return '<div class="loading"><span class="spinner"></span><p>운영 상태 확인 중...</p></div>';
  const rows=[['서류 자동 진행',s.auto_ax,'자료 수신 후 검증과 다음 작업을 연결합니다.'],['원문·추출값 검증',s.ollama?.available,'민감한 원문을 외부로 보내지 않고 확인합니다.'],['스캔 서류 판독',s.ocr?.available,'스캔된 문서에서 텍스트를 읽어냅니다.'],['법률계산',s.legal_calculator?.available,'근거에 연결된 입력값으로 변제계획을 계산합니다.']];
  return `<div class="page-heading"><div><div class="eyebrow">WORKSPACE STATUS</div><h1>운영 현황</h1><p class="page-subtitle">사건을 진행하는 데 필요한 기능의 준비 상태를 확인합니다.</p></div><button class="button secondary" data-action="refresh">${icon('refresh')} 다시 확인</button></div><section class="card"><div class="card-head"><h2>업무 준비 상태</h2>${badge('verified','서버 연결됨')}</div><div class="card-body">${rows.map(([title,ready,detail])=>`<div class="task-row"><div class="task-icon">${icon(ready?'check':'clock')}</div><div style="flex:1"><strong>${esc(title)}</strong><p>${esc(detail)}</p></div>${badge(ready?'verified':'blocked',ready?'사용 가능':'연결 확인 필요')}</div>`).join('')}<div class="task-row"><div class="task-icon">${icon('file')}</div><div style="flex:1"><strong>법령·판례·법원 자료</strong><p>수집한 원문과 적용 범위를 확인합니다.</p></div><button class="button secondary small" data-nav="knowledge">지식함 열기</button></div></div></section>`;
}

function evidenceInput(selected=[]){const docs=list(state.current.documents);return `<fieldset data-evidence style="border:1px solid var(--line);border-radius:9px;padding:14px;margin:0 0 17px"><legend class="small">원문 증거 선택 (검증 완료 자료)</legend>${docs.length?docs.map(d=>`<label class="row small" style="padding:5px 0"><input type="checkbox" name="evidence_ids" value="${esc(d.id)}" ${selected.includes(d.id)?'checked':''} ${d.status!=='verified'?'disabled':''}><span>${esc(d.filename||d.name)}</span>${statusBadge(d)}</label>`).join(''):'<p class="small muted">먼저 자료를 업로드하고 원문 대조를 완료하세요.</p>'}</fieldset>`;}
function docSelect(name,title,required=true){return `<label class="field"><span>${esc(title)}</span><select name="${name}" ${required?'required':''}><option value="">원문 선택</option>${list(state.current.documents).map(d=>`<option value="${esc(d.id)}">${esc(d.filename||d.name)}</option>`).join('')}</select></label>`;}
function openForm(title,html,submit,onSubmit){const expected=state.current?.version;const el=modal(title,`<form id="action-form">${html}<div id="form-error" class="small" role="alert" style="color:#a64b28;white-space:pre-line"></div><div class="form-footer"><button class="button" type="submit">${esc(submit)}</button></div></form>`);el.querySelector('form').onsubmit=async e=>{e.preventDefault();const form=e.target;const btn=form.querySelector('[type=submit]');btn.disabled=true;const fd=new FormData(form);const body=Object.fromEntries(fd);if(form.querySelector('[data-evidence]'))body.evidence_ids=fd.getAll('evidence_ids');body.expected_version=expected;try{await onSubmit(body,fd);el.close();}catch(error){el.querySelector('#form-error').textContent=error.message;}finally{btn.disabled=false;}};return el;}
async function mutate(suffix,body,message){const result=await api(cpath(suffix),{method:'POST',body:{expected_version:state.current.version,...body}});state.current=result.case||result;notify(message);await load();}
async function saveConsultation(data){
  if(state.current.intake?.status==='received')throw new Error('세부 상담을 먼저 요청한 뒤 상담 기록을 완료해 주세요.');
  const answers=Object.fromEntries(consultationQuestions.map(([key])=>[key,data[key]||'']));
  if([data.notes||'',...Object.values(answers)].join('').trim().length<10)throw new Error('세부 상담 내용을 10자 이상 기록해 주세요.');
  if(data.consent!=='on')throw new Error('상담 기록과 자료 활용 동의를 확인해 주세요.');
  await mutate('/consultation',{notes:data.notes||'',answers,consent:true},'세부 상담을 완료했습니다. 기록한 내용에서 추출을 시작합니다.');
}
const actions={
  'consultation-request':()=>openForm('세부 상담 요청',`<p class="small muted">고객 포털의 메시지와 알림으로 전달됩니다. 확인할 내용과 상담 방법을 정리해 주세요.</p>${fields([['message','고객에게 보낼 상담 안내','textarea',defaultConsultationRequest,true]])}`,'세부 상담 요청 보내기',async body=>{if(body.message.trim().length<10||body.message.length>4000)throw new Error('상담 안내를 10자 이상 4,000자 이하로 작성해 주세요.');await mutate('/consultation/request',body,'세부 상담을 요청했습니다. 고객 답변이나 통화 내용을 기록해 주세요.');}),
  'page-prev':async()=>{state.offset=Math.max(0,state.offset-25);state.query='';state.filter='all';await load();},
  'page-next':async()=>{state.offset+=25;state.query='';state.filter='all';await load();},
  menu:()=>document.querySelector('.sidebar').classList.toggle('open'),
  logout:async()=>{clearWorkspace();await logout();authenticate('office',ready);},
  refresh:async()=>{if(state.view==='system')state.system=await api('/system');if(state.view==='registry')state.registry=await api('/registry');if(state.view==='knowledge')await ax.loadKnowledge();await load();},
  'new-case':async()=>{const r=await registry();openForm('새 사건 등록',fields([['client_name','의뢰인 이름','text','',true]])+`<label class="field"><span>검토할 법원</span><select name="court_id" required>${list(r.courts).map(c=>`<option value="${esc(c.id)}">${esc(c.name)}</option>`).join('')}</select></label>`+fields([['summary','상담 요약','textarea','',true]])+'<label class="row small"><input name="consent" type="checkbox" required> 의뢰인의 사건 기록 작성 동의를 확인했습니다.</label>','사건 등록',async body=>{const c=await api('/cases',{method:'POST',body:{client_name:body.client_name,court_id:body.court_id,summary:body.summary,consent:true}});await load();await openCase((c.case||c).id);notify('사건을 등록했습니다.');});},
  upload:()=>openBatchUpload({caseData:state.current,role:'staff',isCurrent:()=>Boolean(session.token)&&session.user?.role!=='client',onComplete:async updated=>{state.current=updated;await load();}}),
  'download-doc':async d=>download(cpath('/documents/'+encodeURIComponent(d.id)+'/download'),docName(d.id)),
  'verify-doc':d=>documentReview.open(d.id),
  'document-extractions':d=>documentReview.open(d.id),
  'document-link-request':d=>documentReview.linkRequest(d.id),
  'confirm-fact':d=>{const f=state.current.facts.find(x=>x.id===d.id);openForm(f.label+' 확인',fields([['value',f.label+' (원)','number',f.value??'',true]])+evidenceInput(f.evidence_ids)+fields([['reason','원문 대조 및 확정 이유','textarea',f.reason||'',true]]),'사실 확정',body=>mutate('/facts/'+encodeURIComponent(d.id)+'/confirm',{...body,value:Number(body.value)},'근거에 연결된 사실을 확정했습니다. 이전 계산과 승인은 재검토가 필요합니다.'));},
  decide:d=>{const i=state.current.issues.find(x=>x.id===d.id);openForm('쟁점 판단 · '+i.title,fields([['decision','채택한 판단','textarea',i.decision||'',true],['reason','쟁점별 판단 이유와 잔존 위험','textarea',i.reason||'',true]])+evidenceInput(i.evidence_ids),'판단 기록',body=>mutate('/issues/'+encodeURIComponent(d.id)+'/decide',body,'변호사의 개별 판단을 기록했습니다.'));},
  request:async()=>{const r=await registry();openForm('고객에게 자료 요청',`<label class="field"><span>요청할 서류</span><select name="catalog_id" required>${list(r.documents).map(d=>`<option value="${esc(d.id)}">${esc(d.name)} · ${esc(d.issuer)}</option>`).join('')}</select></label>`+fields([['period','필요한 기간·범위','text','',true],['reason','요청 이유와 제출 안내','textarea','',true]]),'자료 요청 등록',body=>mutate('/requests',body,'고객 포털에 자료 요청을 등록했습니다.'));},
  'make-bundle':()=>mutate('/bundles',{},'현재 자료 버전의 검토본을 생성했습니다.'),
  'download-bundle':d=>download(cpath('/bundles/'+encodeURIComponent(d.id)+'/download'),`빚오프_검토본_${state.current.id}.html`),
  'approve-bundle':d=>openForm('문서 검토 승인',`<div class="callout neutral" style="margin-bottom:18px">검토용 보고서 승인입니다. 법원 제출 승인이 아닙니다.</div>`+fields([['reason','검토 범위와 승인 이유','textarea','',true]]),'검토 승인 기록',body=>mutate('/bundles/'+encodeURIComponent(d.id)+'/approve',body,'검토 승인과 대상 버전을 기록했습니다.')),
  'gate-approve':()=>openForm('상담 검토 H1',fields([['reason','상담 검토 내용과 승인 이유','textarea','',true]]),'H1 기록',body=>mutate('/approvals',{...body,gate:'H1'},'상담 검토를 기록했습니다.')),
  'new-correction':()=>openForm('법원 보정 요구 등록',fields([['title','보정 항목 제목','text','',true],['requirement','원문의 요구 사항','textarea','',true],['period','요구한 기간·계좌·범위','text','',true]])+docSelect('source_document_id','법원 요구 원문')+fields([['source_page','원문 페이지','number','1',true],['due_date','확인된 제출 기한 (선택)','date','']])+docSelect('deadline_evidence_id','송달일·기한 근거 (기한 입력 시 필수)',false),'보정 항목 등록',body=>mutate('/corrections',{...body,source_page:Number(body.source_page),due_date:body.due_date||null,deadline_evidence_id:body.deadline_evidence_id||null},'보정 요구를 원문과 연결했습니다.')),
  'respond-correction':d=>{const r=state.current.corrections.find(x=>x.id===d.id);openForm('보정 답변 검토 · '+r.title,fields([['answer','확인 사실·소명 내용·변경 문서','textarea',r.answer||'',true]])+evidenceInput(r.evidence_ids)+fields([['reason','요구 충족 여부와 남은 확인 사항','textarea','',true]]),'답변 검토 저장',body=>mutate('/corrections/'+encodeURIComponent(d.id)+'/respond',body,'보정 답변과 증거를 저장했습니다.'));},
  'approve-correction':d=>openForm('보정 항목 검토 승인 H-C',fields([['reason','원문 요구 충족 확인과 승인 이유','textarea','',true]]),'H-C 승인 기록',body=>mutate('/corrections/'+encodeURIComponent(d.id)+'/approve',body,'보정 항목의 검토 승인을 기록했습니다.')),
  workflow:()=>openForm('사건 업무 상태 변경',`<label class="field"><span>다음 업무 상태</span><select name="stage">${['자료 수집','검증 중','보정 대응','검토 보류'].map(s=>`<option ${state.current.stage===s?'selected':''}>${s}</option>`).join('')}</select></label>`+fields([['reason','상태 변경 이유와 다음 조치','textarea','',true]]),'업무 상태 저장',body=>mutate('/workflow',body,'사건 업무 상태와 변경 사유를 기록했습니다.')),
  'confirm-deadline':d=>openForm('송달 근거와 기한 확인',fields([['due_date','원문으로 확인한 기한','date','',true]])+docSelect('evidence_id','검증 완료된 송달·기한 근거')+fields([['reason','기한 산정 및 원문 대조 이유','textarea','',true]]),'기한 확정',body=>mutate('/deadlines/'+encodeURIComponent(d.id)+'/confirm',body,'기한과 확인 근거를 기록했습니다.')),
  submission:()=>{state.tab='bundles';render();},
  'run-agent':d=>consultationPending(state.current)?go('case','consultation'):ax.start(d.kind),
  requirements:async()=>{const data=await api('/requirements');modal('요구조건과 구현 범위',structuredHtml(data));},
  'sample-bundle':()=>download('/testing/sample-bundle'+(state.current?.id?'?case_id='+encodeURIComponent(state.current.id):''),'새출발_연습자료.zip'),
  prompts:async()=>{const data=await api('/prompts');modal('AI 프롬프트 · 버전과 실행 위치',`<p class="small muted">apps/api/prompts/의 파일이 실제 모델 호출에 사용됩니다. 서류 규칙·계산 산식은 별도 코드로 실행됩니다.</p>${data.prompts.map(p=>`<details class="section-spacer"><summary>${esc(p.title)} · ${esc(p.id)} · v${esc(p.version)}</summary><p class="small muted">${esc(p.path)}<br>호출: ${esc(p.caller)}<br>SHA-256: ${esc(p.sha256)}</p><pre class="code-block">${esc(p.text)}</pre></details>`).join('')}`);},
  'ocr-detail':d=>{const doc=state.current.documents.find(x=>x.id===d.id);modal('스캔 OCR · 쪽별 판독 근거',ocrDetail(doc));}
};
document.addEventListener('click',async e=>{const nav=e.target.closest('[data-nav]');const tab=e.target.closest('[data-tab]');const row=e.target.closest('[data-case]');const action=e.target.closest('[data-action]');try{if(nav){go(nav.dataset.nav);if(state.view==='registry'){await registry();render();}if(state.view==='system'){state.system=await api('/system');render();}if(state.view==='knowledge'){await Promise.all([ax.loadKnowledge(),registry()]);ax.repaint();}return;}if(tab){state.tab=tab.dataset.tab;if(state.current)state.view='case';render();return;}if(row&&!action){await openCase(row.dataset.case);return;}if(action){const fn=actions[action.dataset.action]||automation.actions[action.dataset.action]||ax.actions[action.dataset.action]||legalTools.actions[action.dataset.action]||filing.actions[action.dataset.action];if(fn){action.disabled=true;await fn(action.dataset);action.disabled=false;}}}catch(error){notify(error.message,'error');if(action)action.disabled=false;}});
document.addEventListener('toggle',e=>{if(e.target.isConnected&&e.target.matches?.('.case-dashboard-history'))state.dashboardHistory={caseId:state.current?.id,open:e.target.open};},true);
document.addEventListener('keydown',e=>{if(e.key==='Enter'&&e.target.matches('tr[data-case]'))openCase(e.target.dataset.case);});
document.addEventListener('input',e=>{if(e.target.id==='case-search'){state.query=e.target.value;document.querySelector('#cases-table').innerHTML=casesTable();}});
document.addEventListener('change',async e=>{if(e.target.id==='case-filter'){state.filter=e.target.value;document.querySelector('#cases-table').innerHTML=casesTable();}if(e.target.id==='agent-case'&&e.target.value){try{state.current=await api('/cases/'+encodeURIComponent(e.target.value));render();}catch(error){notify(error.message,'error');}}});
document.addEventListener('submit',async e=>{if(!['calculate-form','message-form','consultation-form','legal-search-form'].includes(e.target.id))return;e.preventDefault();const btn=e.target.querySelector('[type=submit]');btn.disabled=true;try{const data=Object.fromEntries(new FormData(e.target));if(e.target.id==='legal-search-form'){state.legalQuery=data.q;state.legalTarget=data.target;state.legalResults=await api('/legal/search?q='+encodeURIComponent(data.q)+'&target='+encodeURIComponent(data.target));render();}else if(e.target.id==='consultation-form'){await saveConsultation(data);}else if(e.target.id==='calculate-form'){await mutate('/calculate',{mode:'scenario',...Object.fromEntries(Object.entries(data).map(([k,v])=>[k,Number(v)]))},'가정 현금흐름을 계산했습니다.');}else{await mutate('/messages',data,'고객 포털에 메시지를 전달했습니다.');}}catch(error){notify(error.message,'error');}finally{btn.disabled=false;}});
window.addEventListener('session-expired',()=>{clearWorkspace();authenticate('office',ready);});
authenticate('office',ready);
