import {esc,date,list,badge,icon,fields} from '/shared/ui.js';

export const consultationPending=c=>Boolean(c?.intake&&['received','consultation_requested'].includes(c.intake.status));
export const consultationQuestions=[['income','현재 소득 형태·세전/세후 금액·변동'],['household','실제 부양가족과 각 가족의 소득'],['assets','부동산·보증금·자동차·보험 등 재산'],['debts','채권자·담보·추심과 채권 변동'],['housing','거주 형태·주거비와 계약 기간'],['recent_transactions','최근 차입·처분·가족 송금·완납 내역'],['history','과거 회생·파산·면책·진행 절차'],['unknowns','아직 확인되지 않은 내용과 추가 질문']];
export const defaultConsultationRequest='상담 신청을 확인했습니다. 세부 상담을 위해 현재 소득과 가족 구성, 재산·채무, 거주 상황과 최근 거래 내용을 알려주세요. 통화가 가능한 시간도 함께 남겨주시면 담당자가 연락드리겠습니다. 확인되지 않은 내용은 모른다고 말씀해 주셔도 됩니다.';

export function consultationView(c){
  const record=c.consultation||{},intake=c.intake,waiting=intake?.status==='received';
  const statusNames={received:'상담 신청 접수',consultation_requested:'세부 상담 진행 중',completed:'세부 상담 완료'};
  const replies=list(c.messages).filter(m=>m.role==='client'&&(!intake?.requested_at||String(m.created_at)>=String(intake.requested_at)));
  const application=intake?`<section class="card consultation-application"><div class="card-head"><div><div class="overline">APPLICATION</div><h2>고객이 남긴 상담 신청</h2></div>${badge(intake.status==='completed'?'verified':'pending',statusNames[intake.status]||'접수 확인')}</div><div class="card-body"><p class="small muted">접수 ${date(intake.submitted_at,true)} · 신청 내용은 원문 그대로 보관하며 추출에 사용하지 않습니다.</p><div class="consultation-original" data-original-text>${esc(intake.application_notes||'신청 본문이 없습니다.')}</div><div class="row between wrap consultation-request-action"><p class="small muted">${waiting?'필요한 상담 내용을 고객에게 요청한 뒤 상담 기록을 작성하세요.':intake.status==='completed'?'담당자가 완료한 세부 상담 기록을 기준으로 추출합니다.':'고객 답변이나 통화에서 확인한 내용을 아래 상담 기록에 정리하세요.'}</p>${waiting?`<button class="button" data-action="consultation-request">${icon('message')} 세부 상담 요청</button>`:''}</div>${intake.request_message?`<details class="section-spacer"><summary>고객에게 보낸 세부 상담 요청 · ${date(intake.requested_at,true)}</summary><p class="consultation-original" data-original-text>${esc(intake.request_message)}</p></details>`:''}${intake.status==='consultation_requested'?`<div class="consultation-replies"><div class="row between"><h3>고객의 추가 답변</h3><button class="button subtle small" data-tab="messages">대화 전체 보기</button></div>${replies.length?replies.map(m=>`<article><p class="consultation-original" data-original-text>${esc(m.text)}</p><small class="muted">${date(m.created_at,true)}</small></article>`).join(''):'<p class="small muted">아직 새 답변이 없습니다. 전화·대면 상담을 진행했다면 아래에 직접 기록할 수 있습니다.</p>'}</div>`:''}</div></section>`:'';
  return `${application}<div class="callout neutral consultation-guidance">${icon('info')}<div><strong>세부 상담 기록에서 필요한 내용을 추출합니다.</strong><br>고객 신청과 추가 답변을 확인하고 담당자가 상담 내용을 정리해 주세요. 상담 완료 후에도 진술은 원문 대조 전까지 확정된 사실로 취급하지 않습니다.</div></div><section class="card"><div class="card-head"><div><h2>담당자 세부 상담 기록</h2>${intake?.completed_at?`<p class="small muted">상담 완료 ${date(intake.completed_at,true)}</p>`:''}</div><button class="button secondary small" data-action="workflow">업무 상태 변경</button></div><form id="consultation-form" class="card-body" aria-describedby="consultation-save-guide"><fieldset class="consultation-fields" ${waiting?'disabled':''}><div class="field-grid">${consultationQuestions.map(([key,title])=>`<label class="field"><span>${title}</span><textarea name="${key}">${esc(record.answers?.[key]||'')}</textarea></label>`).join('')}</div>${fields([['notes','세부 상담 종합 기록 · 확인한 내용과 남은 질문','textarea',record.notes||'']])}<label class="row small"><input type="checkbox" name="consent" ${record.consent?'checked':''} required> 고객에게 상담 기록과 자료 활용을 안내하고 동의를 확인했습니다.</label><p id="consultation-save-guide" class="small muted consultation-save-guide">${waiting?'먼저 위의 세부 상담 요청을 고객에게 보내주세요.':'상담 내용을 10자 이상 기록해 주세요. 상담을 완료하면 이 기록을 저장하고 추출·필요서류 선정을 시작합니다.'}</p><div class="form-footer"><button class="button" type="submit">상담 완료·추출 시작</button></div></fieldset></form></section>`;
}
