import React,{useEffect,useRef,useState} from 'react';
import {date,icon,list} from '../../shared/ui.js';
import {humanText} from '../../shared/structured.js';
import ApprovalEstimate from './ApprovalEstimate.jsx';

const tabs=new Set(['overview','consultation','verify','issues','calculate','court_forms','bundles','corrections','messages']);
const target=value=>tabs.has(value)?value:({ocr:'verify',legal:'issues',documents:'verify'})[value]||'verify';
const phaseNames={consultation:'세부 상담',consultation_waiting:'세부 상담',collecting:'서류 준비',validation:'자료 확인',extraction:'내용 추출',ocr_verification:'추출값 대조',verification_waiting:'추출·검증 확인',legal_analysis:'법률 검토·계산',lawyer_review:'법률 검토',drafting:'1차 서류 작성',document_verification:'작성본 검토',human_review:'보완·최종 승인',submission_ready:'제출 준비',submitted:'제출 기록 완료',completed:'검토 결과 확인'};
const categoryNames={documents:'서류 보완',legal:'법률 검토',supporting:'근거 확인'};
const statusNames={met:'기준 확인',unmet:'보완 필요',unknown:'판단 대기',not_applicable:'적용 제외',covered:'확인됨',extracted:'추출 완료 · 검토 전',missing:'자료 필요',pending:'확인 대기',verified:'검토 완료',received:'검토 대기',completed:'추출 완료',running:'추출 중',failed:'추출 재확인'};
const number=value=>typeof value==='number'&&Number.isFinite(value)&&value>=0?value:null;
const count=value=>number(value)??0;
const text=value=>{const raw=typeof value==='string'?value:value?.message||value?.summary||value?.description||value?.reason||value?.title||'';return raw?humanText(raw).replace(/\b(?:case|typed|mapped|doc|policy)-[a-z0-9_-]{7,}\b/gi,'사건 기록').replace(/\b[a-f0-9]{32,64}\b/gi,'검토 기준').replace(/\b(?:llama\S*|ollama|deepseek\S*|gpt-[\w.-]+)\b/gi,'AI'):'';};
const officialURL=value=>{try{const url=new URL(value);return url.protocol==='https:'&&/(^|\.)(law\.go\.kr|scourt\.go\.kr|court\.go\.kr|moleg\.go\.kr)$/.test(url.hostname)?url.href:null;}catch{return null;}};
const refs=item=>list(item?.source_refs||item?.sources||(item?.source?[item.source]:[])).filter(s=>s&&typeof s==='object');
const courtScope=(value,c)=>value==='national'?'전국 적용 법리':/^CT\d+$/.test(value||'')?(value===c.court_id?text(c.court_name):({'CT01':'서울회생법원','CT02':'수원회생법원','CT03':'부산회생법원'})[value]||'해당 관할 법원 기준'):text(value);
const decisionStage=value=>({application:'개시신청 단계',post_approval:'인가 이후 단계',discharge:'면책 단계'})[value]||(/^[a-z_]+$/.test(value||'')?'절차 단계 확인 필요':text(value));
const outcomeLabel=value=>({remanded:'파기환송',discharge_affirmed:'면책 결정 유지'})[value]||(/^[a-z_]+$/.test(value||'')?'결정 내용은 원문에서 확인':text(value));
const stepState={waiting:'대기',running:'진행 중',completed:'완료',blocked:'보완 필요',failed:'재확인 필요',review_required:'담당자 확인 필요'};
const defaultSteps=[['collection','자료 수집'],['validation','서류 검토'],['ocr','원문 대조'],['analysis','법률 판단·계산'],['draft','1차 작성'],['review','작성본 검토'],['human_review','보완·최종 승인'],['submission','제출 기록']];
const stepTab={collection:'verify',validation:'verify',ocr:'verify',analysis:'issues',draft:'court_forms',review:'court_forms',human_review:'bundles',submission:'bundles'};
function Icon({name}){return <span className="cd-icon" aria-hidden="true" dangerouslySetInnerHTML={{__html:icon(name)}}/>;}
function LinkButton({tab,children,...props}){return <button className="cd-link" data-tab={target(tab)} {...props}>{children}<Icon name="arrow"/></button>;}
function SourceLinks({sources}){return <div className="cd-source-links">{list(sources).map((source,index)=>{const url=officialURL(source.url||source.source_url);return url?<a href={url} target="_blank" rel="noopener noreferrer" key={index}>{text(source.title||source.locator)||'공식 원문'}<Icon name="arrow"/></a>:null;})}</div>;}
function Ring({value,total,label,neutral=false}){const valid=number(total)>0&&number(value)!==null,ratio=valid?Math.min(1,value/total):0;return <svg className={`cd-ring ${neutral?'is-neutral':''}`} viewBox="0 0 104 104" role="img" aria-label={valid?`${label} ${value} / ${total}`:`${label} 확인 대기`}><circle className="cd-ring-track" cx="52" cy="52" r="42"/><circle className="cd-ring-value" cx="52" cy="52" r="42" pathLength="100" strokeDasharray={`${ratio*100} 100`} transform="rotate(-90 52 52)"/><text x="52" y="57" textAnchor="middle">{valid?Math.round(ratio*100)+'%':'—'}</text></svg>;}
function RuleBars({metric}){const values=[count(metric.met),count(metric.unmet),count(metric.unknown)],total=values.reduce((a,b)=>a+b,0);return <div className="cd-rule-chart" aria-label={`기준 확인 ${values[0]}개, 보완 ${values[1]}개, 판단 대기 ${values[2]}개`}><div className="cd-stacked-bar">{total?values.map((value,index)=><span key={index} className={['met','unmet','unknown'][index]} style={{width:`${value/total*100}%`}}/>):<span className="unknown" style={{width:'100%'}}/>}</div><div className="cd-chart-legend"><span><i className="met"/>확인 {values[0]}</span><span><i className="unmet"/>보완 {values[1]}</span><span><i className="unknown"/>대기 {values[2]}</span></div></div>;}
function Empty({children}){return <p className="cd-empty">{children}</p>;}
function nextAction(c,assessment){const intake=c.intake?.status,p=c.ax_pipeline||{};if(['received','consultation_requested'].includes(intake))return {title:intake==='received'?'신청 내용을 확인하고 세부 상담을 요청하세요.':'세부 상담 내용을 기록해 주세요.',label:'상담 이어가기',tab:'consultation'};if(['human_review','completed','submission_ready','submitted'].includes(p.stage))return {title:p.stage==='submitted'?'제출 기록과 이후 보정 요구를 확인하세요.':'작성본을 확인하고 보완·최종 승인을 진행하세요.',label:p.stage==='submitted'?'제출 기록 확인':'작성본·최종 검토',tab:'bundles'};if(p.stage==='verification_waiting')return {title:'서류별 추출과 원문 대조를 확인해 주세요.',label:'자료 확인하기',tab:'verify'};const action=list(assessment.actions)[0];if(action)return {title:text(action.title)||'다음 검토 항목을 확인하세요.',label:'우선 항목 확인',tab:target(action.target?.tab)};return {title:c.documents?.length?'확인된 자료를 바탕으로 다음 단계를 준비합니다.':'상담과 증빙자료에서 사건 검토를 시작합니다.',label:c.documents?.length?'자료 확인하기':'상담 기록 열기',tab:c.documents?.length?'verify':'consultation'};}

function Details({selection,close,c,a}){
  const dialog=useRef(null),kind=selection?.kind,item=selection?.item;
  useEffect(()=>{const el=dialog.current;if(selection&&el&&!el.open)el.showModal();return()=>{if(el?.open)el.close();};},[selection]);
  if(!selection)return null;
  const titles={source:'자료에서 확인한 항목',rules:'적용 법률 기준',risks:'위험과 확인할 판단',approval:'인가 가능성의 근거',action:'검토 항목 상세',actions:'검토 항목 전체',knowledge:'연결된 법령·판례',deadlines:'확인할 기한'};
  return <dialog ref={dialog} className="cd-dialog" aria-labelledby="cd-detail-title" onCancel={e=>{e.preventDefault();close();}} onClick={e=>{if(e.target===e.currentTarget||e.target.closest('[data-tab],[data-nav],[data-action]'))close();}}><div className="cd-dialog-head"><div><span className="cd-overline">검토 근거</span><h2 id="cd-detail-title">{titles[kind]||'사건 상세'}</h2></div><button className="cd-close" aria-label="상세 닫기" onClick={close}><Icon name="close"/></button></div><div className="cd-dialog-body">
    {kind==='source'&&<><p>공식 서식에 필요한 자료 항목을 기준으로 셉니다. 서류 검토 완료와 모든 법률 판단의 완료는 별개입니다.</p>{list(a.forms).length?list(a.forms).map((form,index)=><details className="cd-form-detail" key={index} open={index===0}><summary>{text(form.title)||'작성 서식'}<span>{count(form.covered)} / {count(form.total)} 확인</span></summary>{list(form.fields).map((field,n)=><div className="cd-detail-row" key={n}><div><strong>{text(field.label)||'확인 항목'}</strong><small>{({source:'원문 근거',legal:'법률 판단',formal:'작성·서명 사항'})[field.category]||'근거 확인'}</small></div><span className={`cd-tag ${field.status==='covered'?'green':'sand'}`}>{statusNames[field.status]||'확인 대기'}</span><LinkButton tab={field.target?.tab||'verify'}>확인</LinkButton></div>)}</details>):<Empty>필수 항목별 평가를 아직 준비하지 못했습니다. 받은 서류에서 원문과 추출 내용을 확인할 수 있습니다.</Empty>}<LinkButton tab="verify">자료 추출·검토 열기</LinkButton></>}
    {kind==='rules'&&<><p>확인된 기준, 충족하지 못한 기준, 아직 판단하지 않은 기준을 나누어 표시합니다. 기준 확인율은 인가 확률이 아닙니다.</p>{list(a.rules).length?list(a.rules).map((rule,index)=><article className="cd-detail-article" key={index}><span className={`cd-tag ${rule.status==='met'?'green':rule.status==='unmet'?'red':'sand'}`}>{statusNames[rule.status]||'판단 대기'}</span><h3>{text(rule.title)||'법률 검토 기준'}</h3><p>{text(rule.summary)}</p>{(rule.actual!==undefined&&rule.actual!==null)&&<p className="cd-evidence-value">확인한 값 · {text(typeof rule.actual==='object'?rule.actual:String(rule.actual))}{text(rule.unit)}</p>}<SourceLinks sources={refs(rule)}/><LinkButton tab={rule.target?.tab||'issues'}>판단과 근거 확인</LinkButton></article>):<Empty>상담과 자료 확인 이후 적용 기준을 평가합니다. 아직 평가하지 않은 기준을 충족한 것으로 표시하지 않습니다.</Empty>}</>}
    {kind==='risks'&&<><p>확인된 위험과 정보 부족으로 남은 판단을 구분합니다.</p><div className="cd-risk-summary"><strong>확인된 위험 <b>{number(a.metrics?.risks?.confirmed)??'—'}</b></strong><strong>판단 대기 <b>{number(a.metrics?.risks?.pending)??'—'}</b></strong></div>{list(a.rules).filter(r=>['unmet','unknown'].includes(r.status)).map((rule,index)=><article className="cd-detail-article" key={index}><span className="cd-tag sand">{statusNames[rule.status]}</span><h3>{text(rule.title)}</h3><p>{text(rule.summary)}</p><SourceLinks sources={refs(rule)}/><LinkButton tab={rule.target?.tab||'issues'}>확인하기</LinkButton></article>)}{!list(a.rules).some(r=>['unmet','unknown'].includes(r.status))&&<Empty>상세 위험은 적용 법률 기준과 담당자의 판단이 기록되면 표시됩니다.</Empty>}<LinkButton tab="issues">법률 쟁점 전체 보기</LinkButton></>}
    {kind==='approval'&&<><p>{text(a.prediction?.reason)||'개별 사건의 인가 확률을 표시할 검증된 예측 자료가 아직 충분하지 않습니다.'}</p><ApprovalEstimate caseData={c}/></>}
    {kind==='action'&&<article className="cd-detail-article"><span className="cd-tag sand">{categoryNames[item?.category]||'검토 항목'}</span><h3>{text(item?.title)}</h3><p>{text(item?.summary||item?.description||item?.reason)}</p>{list(item?.required_evidence).length>0&&<><h4>확인할 자료</h4><ul>{item.required_evidence.map((value,index)=><li key={index}>{text(value)}</li>)}</ul></>}<SourceLinks sources={refs(item)}/><LinkButton tab={item?.target?.tab||'issues'}>해당 업무에서 확인</LinkButton></article>}
    {kind==='actions'&&list(a.actions).filter(action=>action.category===item?.category).map((action,index)=><article className="cd-detail-article" key={index}><span className="cd-tag sand">{categoryNames[action.category]}</span><h3>{text(action.title)}</h3><p>{text(action.summary||action.description||action.reason)}</p><SourceLinks sources={refs(action)}/><LinkButton tab={action.target?.tab}>해당 업무에서 확인</LinkButton></article>)}
    {kind==='knowledge'&&<>{list(item?[item]:a.knowledge?.matches).length?list(item?[item]:a.knowledge?.matches).map((match,index)=><article className="cd-detail-article" key={index}><span className="cd-tag green">{({case:'판례',court_rule:'법원 기준',statute:'법령'})[match.kind]||'공식 근거'}</span><h3>{text(match.title||match.source?.title)}</h3><p>{text(match.summary)}</p>{text(match.court_scope)&&<p className="cd-scope">적용 범위 · {courtScope(match.court_scope,c)}</p>}{(match.decision_stage||match.outcome)&&<p className="cd-scope">{decisionStage(match.decision_stage)}{match.outcome?" · "+outcomeLabel(match.outcome):""}</p>}{list(match.limits).map((limit,n)=><p className="cd-limit" key={n}>{text(limit)}</p>)}{list(match.required_evidence).length>0&&<><h4>적용을 위해 확인할 자료</h4><ul>{match.required_evidence.map((value,n)=><li key={n}>{text(value)}</li>)}</ul></>}{match.source?.excerpt&&<blockquote>{text(match.source.excerpt)}</blockquote>}<SourceLinks sources={[match.source].filter(Boolean)}/></article>):<Empty>이 사건과 연결된 공식 원문을 아직 확인하지 못했습니다. 근거가 확보되면 적용 범위와 함께 표시합니다.</Empty>}<button className="cd-link" data-nav="knowledge">수집 지식함 열기<Icon name="arrow"/></button></>}
    {kind==='deadlines'&&<>{list(c.deadlines).length?c.deadlines.map((deadline,index)=><article className="cd-detail-article" key={index}><h3>{text(deadline.title)||'확인할 기한'}</h3><p>{deadline.due_date?date(deadline.due_date):'송달 근거를 확인한 뒤 기한을 확정해 주세요.'}</p><button className="cd-link" data-action="confirm-deadline" data-id={deadline.id}>근거와 기한 확인<Icon name="arrow"/></button></article>):<Empty>등록된 기한이 없습니다.</Empty>}</>}
  </div><div className="cd-dialog-foot"><button className="button secondary" onClick={close}>닫기</button></div></dialog>;
}

export default function CaseDashboard({caseData:c,initialSelection,onSelection}){
  const a=c.case_assessment||{},m=a.metrics||{},source=m.required_fields?.source||{},rules=m.rules||{},risk=m.risks||{};
  const [selection,setSelection]=useState(initialSelection||null),[category,setCategory]=useState('documents');
  const choose=(kind,item=null)=>{const value={kind,item};setSelection(value);onSelection?.(value);};
  const close=()=>{setSelection(null);onSelection?.(null);};
  const p=c.ax_pipeline||{},pendingConsultation=['received','consultation_requested'].includes(c.intake?.status),running=p.active_run?.status==='running'||p.status==='running';
  const phase=pendingConsultation?'세부 상담':phaseNames[p.stage]||'자료 확인·사건 준비';
  const next=nextAction(c,a),steps=list(p.steps).length?list(p.steps):defaultSteps.map(([id,title])=>({id,title,status:'waiting'})),done=steps.filter(s=>s.status==='completed').length;
  const activeStep=steps.find(s=>s.status==='running')||steps.find(s=>s.status!=='completed'),activeDetail=text(activeStep?.detail||p.summary);
  const actions=list(a.actions),selectedActions=actions.filter(action=>action.category===category),matches=list(a.knowledge?.matches),cases=matches.filter(match=>match.kind==='case');
  const references=(cases.length?cases:matches).slice(0,3),documents=list(c.documents).filter(doc=>!['superseded','quarantined','rejected'].includes(doc.status)),verified=number(m.documents?.verified)??documents.filter(doc=>doc.status==='verified').length,documentTotal=number(m.documents?.total)??documents.length;
  const totalRules=count(rules.met)+count(rules.unmet)+count(rules.unknown),progress=p.progress,progressTotal=count(progress?.total),progressDone=Math.min(progressTotal,count(progress?.completed));
  const currentDrafts=list(c.court_documents).filter(doc=>!doc.stale&&doc.status!=='superseded');
  return <div className="case-dashboard" data-react-component="CaseDashboard">
    <section className="cd-hero" aria-label="현재 단계와 다음 업무"><div className="cd-hero-main"><div className="cd-hero-kicker"><span className={`cd-live-dot ${running?'active':''}`}/>{running?'지금 진행 중':'현재 진행 단계'}<span className="cd-phase">{phase}</span></div><h2>{next.title}</h2><p>{running?activeDetail||'확인된 자료를 순서대로 대조하고 있습니다. 진행 상황은 자동으로 갱신됩니다.':text(a.summary?.description)||'원문 확인부터 법률 판단과 문서 작성까지, 필요한 검토를 한곳에서 이어가세요.'}</p><div className="cd-hero-actions"><button className="cd-primary" data-tab={next.tab}>{next.label}<Icon name="arrow"/></button><button className="cd-hero-link" data-tab="messages"><Icon name="message"/>고객 연락</button></div></div><div className="cd-hero-status"><span>진행 기록</span><strong>{done}<small> / {steps.length||8}</small></strong><p>업무 단계 완료</p><div className="cd-step-dots" aria-label={`${done}개 단계 완료`}>{(steps.length?steps:Array.from({length:8},()=>({}))).map((step,index)=><span key={index} className={step.status==='completed'?'complete':step.status==='running'?'active':''}/>)}</div>{progressTotal>0&&<div className="cd-mini-progress"><span>{text(progress.label)||'원문 대조'}</span><b>{progressDone} / {progressTotal}</b><progress value={progressDone} max={progressTotal}/></div>}{p.queued_update?.status==='queued'&&<small className="cd-queue-note">새 자료 반영 대기</small>}</div></section>
    <div className="cd-process"><div className="cd-process-head"><span>진행 순서 · 단계를 눌러 해당 업무로 이동하세요.</span>{!pendingConsultation&&<button className="cd-link" data-action="automation-run" disabled={running||p.queued_update?.status==='queued'||p.status==='queued'}><Icon name="refresh"/>다시 확인</button>}</div><ol className="cd-stepper" aria-label="사건 진행 순서">{steps.map((step,index)=><li key={step.id||index} data-step-status={step.status||'waiting'}><button data-tab={pendingConsultation?'consultation':stepTab[step.id]||'overview'}><span className="cd-step-index">{step.status==='completed'?<Icon name="check"/>:index+1}</span><strong>{text(step.title||step.label)||'진행 단계'}</strong><small>{stepState[step.status]||'대기'}</small></button></li>)}</ol></div>
    <div className="cd-section-heading"><div><span className="cd-overline">사건의 현재 모습</span><h2>숫자와 근거를 함께 확인하세요.</h2></div><span className="cd-hint"><Icon name="info"/>지표를 누르면 상세 내용을 볼 수 있습니다.</span></div>
    <section className="cd-metrics" aria-label="사건 검토 지표">
      <button className="cd-metric" data-dashboard-metric="source" onClick={()=>choose('source')} aria-haspopup="dialog"><div className="cd-metric-title"><span>자료 추출</span><Icon name="arrow"/></div><div className="cd-metric-body"><Ring value={source.covered} total={source.total} label="서식에 필요한 자료 추출"/><div><strong>{number(source.total)>0?`${count(source.covered)} / ${source.total}`:'확인 대기'}</strong><small>원문에서 추출한 항목</small></div></div><p>{number(source.verified)!==null?`항목 ${source.verified}개 확인 완료 · `:''}서류 {verified} / {documentTotal}건 검토</p></button>
      <button className="cd-metric" data-dashboard-metric="rules" onClick={()=>choose('rules')} aria-haspopup="dialog"><div className="cd-metric-title"><span>법률 기준</span><Icon name="arrow"/></div><div className="cd-metric-number">{totalRules?count(rules.met):'—'}<small>{totalRules?` / ${totalRules}개 확인`:'평가 대기'}</small></div><RuleBars metric={rules}/><p>미확인 기준은 판단 대기로 남깁니다.</p></button>
      <button className="cd-metric" data-dashboard-metric="risks" onClick={()=>choose('risks')} aria-haspopup="dialog"><div className="cd-metric-title"><span>확인할 위험</span><Icon name="arrow"/></div><div className="cd-risk-chart"><div><strong>{number(risk.confirmed)??'—'}</strong><span>확인된 위험</span><i style={{width:`${!count(risk.confirmed)?0:Math.max(6,Math.min(100,count(risk.confirmed)/Math.max(1,count(risk.confirmed),count(risk.pending))*100))}%`}}/></div><div><strong>{number(risk.pending)??'—'}</strong><span>판단 대기</span><i style={{width:`${!count(risk.pending)?0:Math.max(6,Math.min(100,count(risk.pending)/Math.max(1,count(risk.confirmed),count(risk.pending))*100))}%`}}/></div></div><p>자료 부족과 확정 위험을 구분합니다.</p></button>
      <button className="cd-metric cd-prediction" data-dashboard-metric="approval" onClick={()=>choose('approval')} aria-haspopup="dialog"><div className="cd-metric-title"><span>인가 가능성</span><Icon name="arrow"/></div><div className="cd-prediction-content"><span className="cd-prediction-icon"><Icon name="scale"/></span><strong>예측 보류</strong><span className="cd-tag sand">검증 자료가 더 필요합니다</span></div><p>확인되지 않은 확률은 표시하지 않습니다.</p></button>
    </section>
    <div className="cd-work-grid"><section className="cd-panel cd-priorities"><div className="cd-panel-heading"><div><span className="cd-overline">다음 검토</span><h2>우선 확인할 항목</h2></div><span className="cd-counter">{actions.length}건</span></div><div className="cd-category-tabs" role="tablist" aria-label="검토 항목 분류">{Object.entries(categoryNames).map(([key,label])=><button key={key} role="tab" aria-selected={category===key} aria-controls="cd-actions-panel" onClick={()=>setCategory(key)}>{label}<span>{actions.filter(a=>a.category===key).length}</span></button>)}</div><div role="tabpanel" id="cd-actions-panel" aria-label={categoryNames[category]}>{selectedActions.length?selectedActions.slice(0,3).map((action,index)=><button className="cd-action-item" key={index} onClick={()=>choose('action',action)} aria-haspopup="dialog"><span className={`cd-action-number ${action.priority==='high'?'attention':''}`}>{String(index+1).padStart(2,'0')}</span><span><strong>{text(action.title)||'확인할 항목'}</strong><small>{text(action.summary)||'필요한 자료와 적용 근거를 확인하세요.'}</small></span><Icon name="chevron"/></button>):<div className="cd-category-empty"><Icon name={category==='documents'?'file':category==='legal'?'scale':'search'}/><strong>{actions.length?'이 분류에 남은 항목이 없습니다.':'검토할 항목을 준비하고 있습니다.'}</strong><p>{actions.length?'다른 분류의 확인 사항도 살펴보세요.':'상담과 자료 확인이 진행되면 필요한 검토를 정리합니다.'}</p></div>}</div><div className="cd-panel-footer"><span>{selectedActions.length>3?`우선 ${Math.min(3,selectedActions.length)}건 표시 · 전체 ${selectedActions.length}건`:category==='legal'?'법률 판단은 근거와 함께 기록합니다.':'현재 자료를 기준으로 확인합니다.'}</span><button className="cd-link" onClick={()=>choose('actions',{category})} aria-haspopup="dialog">전체 보기<Icon name="arrow"/></button></div></section>
      <section className="cd-panel cd-knowledge"><div className="cd-panel-heading"><div><span className="cd-overline">판단의 근거</span><h2>관련 법령·판례</h2></div><button className="cd-subtle" onClick={()=>choose('knowledge')} aria-haspopup="dialog">전체 보기<Icon name="arrow"/></button></div>{references.length?references.map((match,index)=><button className="cd-reference" key={index} onClick={()=>choose('knowledge',match)} aria-haspopup="dialog"><span className="cd-reference-type">{({case:'판례',statute:'법령',court_rule:'법원 기준'})[match.kind]||'공식 근거'}</span><strong>{text(match.title||match.source?.title)||'적용 근거 확인'}</strong><p>{text(match.summary)}</p><span className="cd-reference-foot">원문·적용 범위 확인<Icon name="arrow"/></span></button>):<div className="cd-knowledge-empty"><span className="cd-book-symbol"><Icon name="scale"/></span><strong>근거를 먼저 확인합니다.</strong><p>사건에 연결된 공식 자료가 확보되면<br/>적용 범위와 필요한 증빙을 보여드립니다.</p><button className="cd-link" data-nav="knowledge">수집 지식함 열기<Icon name="arrow"/></button></div>}<p className="cd-knowledge-note">판례의 절차 단계와 사실관계를 함께 확인합니다.</p></section></div>
    <section className="cd-quick-row" aria-label="이어지는 업무"><button onClick={()=>choose('deadlines')} className="cd-quick"><Icon name="clock"/><span><strong>기한 확인</strong><small>{c.deadlines?.length?`${c.deadlines.length}건 · 송달 근거와 함께 확인`:'등록된 기한이 없습니다'}</small></span><Icon name="chevron"/></button><button className="cd-quick" data-tab="court_forms"><Icon name="file"/><span><strong>작성된 법원 서식</strong><small>{currentDrafts.length?`${currentDrafts.length}건 · 원문과 작성 내용을 대조`:'자료 확인 후 1차 작성을 준비합니다'}</small></span><Icon name="chevron"/></button><button className="cd-quick" data-tab="corrections"><Icon name="check"/><span><strong>보정 대응</strong><small>법원 요구·보완 이력 확인</small></span><Icon name="chevron"/></button></section>
    <Details selection={selection} close={close} c={c} a={a}/>
  </div>;
}
export {text as assessmentText,refs,SourceLinks,Icon,LinkButton,RuleBars,courtScope,decisionStage,outcomeLabel};
