import React,{useState} from 'react';
import {date,list} from '../../shared/ui.js';
import {assessmentText as text,refs,SourceLinks,Icon,LinkButton,RuleBars,courtScope,decisionStage,outcomeLabel} from './CaseDashboard.jsx';

const states={met:'기준 확인',unmet:'보완 필요',unknown:'판단 대기',not_applicable:'적용 제외'};
const categories={documents:'서류 보완',legal:'법률 판단',supporting:'근거 확인'};
const reviewStates={passed:'현재 근거 검토됨',needs_review:'추가 판단 필요',unavailable:'검토 응답 확인 필요',stale:'현재 자료로 다시 검토 필요',not_attempted:'자료·계산 확인 후 검토'};
const visibleActions=(a)=>list(a.actions).filter(row=>row.origin!=='ai_strategy_review'||['passed','needs_review'].includes(a.strategy_review?.status));
function shownValue(value,unit){if(value===null||value===undefined)return '확인 전';if(typeof value==='number')return value.toLocaleString('ko-KR')+(unit?' '+text(unit):'');if(typeof value==='boolean')return value?'확인됨':'해당 없음';return text(value)||'상세 근거에서 확인';}
function OriginLabels({sources}){const local=list(sources).filter(s=>s?.title&&!s.url&&!s.source_url);return local.length?<p className="clr-origin">원문 · {local.map(s=>text(s.title)).join(' · ')}</p>:null;}

function Rule({rule}){return <article className={`clr-rule ${rule.status==='unmet'?'attention':''}`}><div className="clr-rule-heading"><h3>{text(rule.title)||'확인할 법률 기준'}</h3><span className={`cd-tag ${rule.status==='met'?'green':rule.status==='unmet'?'red':'sand'}`}>{states[rule.status]||'판단 대기'}</span></div><div className="clr-values"><div><span>현재 확인값</span><strong>{shownValue(rule.actual,rule.unit)}</strong></div><div><span>적용 기준값</span><strong>{shownValue(rule.threshold,rule.unit)}</strong></div></div><p>{text(rule.summary)||'사건 자료와 적용 범위를 확인한 뒤 판단합니다.'}</p><SourceLinks sources={refs(rule)}/><OriginLabels sources={refs(rule)}/><LinkButton tab={rule.target?.tab==='issues'?'calculate':rule.target?.tab||'calculate'}>값·근거 대조</LinkButton></article>;}

function Reference({match,c}){return <details className="clr-reference"><summary><span className="clr-reference-symbol"><Icon name={match.kind==='case'?'scale':'file'}/></span><span><small>{({case:'판례',statute:'법령',court_rule:'법원 기준',practice:'실무 기준',precedent:'판례'})[match.kind]||'공식 근거'} · {courtScope(match.court_scope,c)||'적용 범위 확인'}</small><strong>{text(match.title||match.source?.title)||'공식 근거 확인'}</strong><span className="clr-reference-summary">{text(match.summary)}</span></span><Icon name="chevron"/></summary><div className="clr-reference-body">{(match.decision_stage||match.outcome)&&<div className="clr-case-stage">{decisionStage(match.decision_stage)}{match.outcome?' · '+outcomeLabel(match.outcome):''}</div>}{list(match.limits).map((limit,n)=><p className="cd-limit" key={n}>{text(limit)}</p>)}{match.kind==='case'&&<p className="clr-scope-note">이 판례와 쟁점이 연결된다는 의미이며, 현재 사건의 인가 결과를 예측하는 사례는 아닙니다.</p>}{list(match.required_evidence).length>0&&<><h4>적용 전에 대조할 증빙</h4><ul>{match.required_evidence.map((value,n)=><li key={n}>{text(value)}</li>)}</ul></>}{list(match.actions).length>0&&<><h4>근거에 따른 검토 방향</h4><ul>{match.actions.map((value,n)=><li key={n}>{text(value)}</li>)}</ul></>}{match.source?.excerpt&&<details className="clr-excerpt"><summary>저장한 원문 구간 보기</summary><blockquote>{text(match.source.excerpt)}</blockquote></details>}<SourceLinks sources={[match.source].filter(Boolean)}/></div></details>;}

function Action({action,index}){return <details className="clr-action" open={index===0}><summary><span className="clr-action-index">{String(index+1).padStart(2,'0')}</span><span><small>{categories[action.category]||'추가 확인'}{action.origin==='ai_strategy_review'?' · AI 검토 제안':''}</small><strong>{text(action.title)||'근거 확인'}</strong></span><Icon name="chevron"/></summary><div className="clr-action-body"><p>{text(action.summary)||'담당자가 근거 자료를 확인해 주세요.'}</p>{text(action.reason)&&text(action.reason)!==text(action.summary)&&<p className="clr-origin">판단 근거 · {text(action.reason)}</p>}{list(action.required_evidence).length>0&&<><h4>필요한 증빙</h4><ul>{action.required_evidence.map((value,n)=><li key={n}>{text(value)}</li>)}</ul></>}{list(action.limits).map((value,n)=><p className="cd-limit" key={n}>{text(value)}</p>)}<SourceLinks sources={refs(action)}/><OriginLabels sources={refs(action)}/>{action.target?.tab!=='issues'&&<LinkButton tab={action.target?.tab||'verify'}>보완할 업무 열기</LinkButton>}</div></details>;}

export default function CaseLegalReview({caseData:c,role}){
  const a=c.case_assessment||{},metric=a.metrics?.rules||{},strategy=a.strategy_review||{},matches=list(a.knowledge?.matches),actions=visibleActions(a),rules=list(a.rules),issues=list(c.issues);
  const [filter,setFilter]=useState('all');
  const ordered=rules.slice().sort((x,y)=>({unmet:0,unknown:1,met:2,not_applicable:3}[x.status]??4)-({unmet:0,unknown:1,met:2,not_applicable:3}[y.status]??4));
  const selected=ordered.filter(rule=>filter==='all'||rule.status===filter),reviewStatus=strategy.status||'not_attempted';
  const statusLabel=reviewStates[reviewStatus]||'검토 상태 확인 필요';
  return <div className="case-legal-review" data-react-component="CaseLegalReview">
    <section className="clr-heading"><div><span className="cd-overline">사실에서 판단으로</span><h2>현재 근거로, 필요한 법률 검토를 이어갑니다.</h2><p>확인한 값과 적용 기준을 대조하고, 관련 법령·판례에서 필요한 증빙과 보완 방향을 확인하세요.</p></div><span className="cd-tag sand">{role==='lawyer'?'변호사 판단 권한':'변호사 최종 판단 필요'}</span></section>
    <section className="clr-flow" aria-label="사실과 법률 검토의 연결"><div><Icon name="file"/><strong>확인한 사실</strong><span>원문 · 기간 · 금액의 의미</span></div><Icon name="arrow"/><div><Icon name="scale"/><strong>적용 법률 기준</strong><span>법령 · 관할 · 절차 단계</span></div><Icon name="arrow"/><div><Icon name="check"/><strong>보완과 판단</strong><span>부족한 증빙 · 미충족 요건</span></div></section>
    <div className="clr-status" data-strategy-status={reviewStatus}><Icon name="info"/><div><strong>{statusLabel}</strong><p>{text(strategy.summary)||'자료 확인과 계산이 진행되면 현재 근거를 바탕으로 전략을 검토합니다.'}{reviewStatus==='stale'?' 이전 전략은 현재 사건의 판단으로 사용하지 않습니다.':''}</p></div>{strategy.updated_at&&<time>{date(strategy.updated_at,true)}</time>}</div>
    {a.freshness?.policy_review_required&&<div className="callout warning"><Icon name="info"/><span>법령 변경사항의 시행일과 경과규정을 확인해야 합니다. 종전 기준의 계산을 현재 충족 판단으로 사용하지 않습니다.</span></div>}
    <div className="clr-layout"><main className="clr-main"><section className="cd-panel clr-rules-panel"><div className="cd-panel-heading"><div><span className="cd-overline">현재 값과 기준의 대조</span><h2>무엇을 더 확인해야 하나요?</h2></div><LinkButton tab="calculate">계산 근거</LinkButton></div><RuleBars metric={metric}/><div className="clr-filter" role="tablist" aria-label="법률 기준 상태">{[['all','전체'],['unmet','보완 필요'],['unknown','판단 대기'],['met','기준 확인']].map(([key,label])=><button key={key} role="tab" aria-selected={filter===key} aria-controls="clr-rule-list" onClick={()=>setFilter(key)}>{label}<span>{key==='all'?rules.length:rules.filter(r=>r.status===key).length}</span></button>)}</div><div id="clr-rule-list" role="tabpanel" className="clr-rule-grid">{selected.map((rule,index)=><Rule rule={rule} key={index}/>)}{!selected.length&&<p className="cd-empty">{rules.length?'이 상태에 해당하는 기준이 없습니다.':'자료와 계산 근거를 확인하면 적용 기준별 대조 결과를 표시합니다.'}</p>}</div><p className="clr-footnote">판단 대기는 미충족이나 기각 사유와 다릅니다. 기준 확인 개수는 인가 확률이 아닙니다.</p></section>
      <section className="cd-panel clr-references"><div className="cd-panel-heading"><div><span className="cd-overline">적용 범위를 확인하는 근거</span><h2>연결된 법령·법원 기준·판례</h2></div><span className="cd-counter">{matches.length}건</span></div>{matches.length?matches.map((match,index)=><Reference match={match} c={c} key={index}/>):<p className="cd-empty">현재 사건과 연결된 공식 근거를 아직 확인하지 못했습니다. 원문과 적용 범위가 확인된 자료만 표시합니다.</p>}<div className="cd-panel-footer"><span>단계와 사실관계가 같은지 함께 대조합니다.</span><button className="cd-link" data-nav="knowledge">수집 지식함<Icon name="arrow"/></button></div></section>
    </main><aside className="cd-panel clr-actions"><div className="cd-panel-heading"><div><span className="cd-overline">먼저 확인할 일부터</span><h2>증빙·보완 순서</h2></div><span className="cd-counter">{actions.length}건</span></div><p className="clr-actions-intro">확인된 부족 항목과 법률 판단, 판례 적용에 필요한 추가 근거를 우선순위대로 정리했습니다.</p>{actions.slice(0,5).map((action,index)=><Action action={action} index={index} key={index}/>)}{actions.length>5&&<details className="clr-more"><summary>나머지 보완 항목 {actions.length-5}건</summary>{actions.slice(5).map((action,index)=><Action action={action} index={index+5} key={index}/>)}</details>}{!actions.length&&<p className="cd-empty">아직 보완 순서를 정할 근거가 충분하지 않습니다. 자료 확인 상태부터 살펴보세요.</p>}<div className="cd-panel-footer"><LinkButton tab="verify">자료 확인</LinkButton><LinkButton tab="messages">고객에게 문의</LinkButton></div></aside></div>
    <details className="clr-decisions"><summary>담당자의 쟁점 판단과 기존 기록 <span>{issues.length}건</span></summary><div>{issues.length?issues.map((issue,index)=><article className="clr-decision" key={index}><h3>{text(issue.title)||'검토한 쟁점'}</h3><p>{text(issue.description)}</p>{list(issue.evidence_ids).length>0&&<p className="clr-origin">연결 자료 · {issue.evidence_ids.map(id=>{const doc=list(c.documents).find(d=>d.id===id);return text(doc?.name||doc?.filename)||'원문 연결 확인 필요';}).join(' · ')}</p>}{list(issue.counter_evidence).length>0&&<p>남은 위험 · {issue.counter_evidence.map(text).join(' · ')}</p>}{list(issue.options).length>0&&<details><summary>기록된 검토 방향</summary>{issue.options.map((option,n)=><p key={n}>{text(option)}</p>)}</details>}<div className="clr-decision-record"><strong>{text(issue.decision)||'아직 판단을 기록하지 않았습니다.'}</strong>{issue.reason&&<p>{text(issue.reason)}</p>}{issue.decided_at&&<small>{date(issue.decided_at,true)}</small>}</div>{role==='lawyer'&&<button className="button secondary small" data-action="decide" data-id={issue.id}>쟁점 판단 기록<Icon name="arrow"/></button>}</article>):<p className="cd-empty">개별 판단 기록이 없습니다. 현재 법률 기준과 증빙을 확인하면서 필요한 판단을 남깁니다.</p>}<LinkButton tab="overview">자동 진행·검토 이력 확인</LinkButton></div></details>
  </div>;
}
