import React from 'react';
import LegalUpdates from './LegalUpdates.jsx';
import ApprovalEstimate from './ApprovalEstimate.jsx';
import {createRoot} from 'react-dom/client';
import {flushSync} from 'react-dom';
import {icon,brand,date,list,legalBasisLabel,readableText} from '../../shared/ui.js';
import {humanText} from '../../shared/structured.js';
import {calculationBlockerTitle} from '../../shared/legal-labels.js';
import {requestWithdrawn,requestNeedsUpload,requestScope,requestOptions,requestFeedback} from '../../shared/requests.js';

const stageNames={consultation:'세부 상담',consultation_waiting:'세부 상담 대기',collecting:'서류 준비·보완',extraction:'상담·서류 내용 추출',validation:'제출 자료 검증',ocr_verification:'추출값 검증',verification_waiting:'검증 재시도 필요',legal_analysis:'쟁점·계산 분석',lawyer_review:'변호사 검토 필요',drafting:'1차 문서 자동 작성',document_verification:'AI 문서 검토',human_review:'담당자 보완·승인',submission_ready:'제출 준비',submitted:'법원 제출 기록 완료',completed:'자동 검토 완료'};
const stepNames={waiting:'대기',running:'진행 중',completed:'완료',blocked:'보완 필요',review_required:'담당자 확인 필요',failed:'재확인 필요'};
const requestNames={fulfilled:'확인 완료',received:'제출 확인 중',validating:'제출 확인 중',processing:'제출 확인 중',requested:'제출 필요',missing:'제출 필요',needs_review:'추가 확인',needs_more:'다시 제출 필요',rejected:'다시 제출 필요',withdrawn:'요청 철회',cancelled:'요청 철회',superseded:'새 요청으로 변경'};
const roots=new Map();
let pipelineRoots=[];
const explanation=value=>humanText(typeof value==='string'?value:value?.message||value?.description||value?.reason||value?.title||'');
const safeURL=url=>{try{const u=new URL(url);return ['https:','http:'].includes(u.protocol)?u.href:null;}catch{return null;}};
function Html({html,className='',as:Tag='span'}){return <Tag className={className} dangerouslySetInnerHTML={{__html:html}}/>;}
function Icon({name}){return <Html html={icon(name)} className="react-icon"/>;}
function Button({children,action,tab,secondary=false,...props}){return <button className={`button ${secondary?'secondary':''}`} data-action={action} data-tab={tab} {...props}>{children}</button>;}
function Pill({status,children}){const color=['fulfilled','completed','verified'].includes(status)?'green':['rejected','needs_more','blocked','lawyer_review','verification_waiting'].includes(status)?'orange':status==='running'?'blue':'gray';return <span className={`badge ${color}`}>{children}</span>;}
function Empty({title,detail}){return <div className="empty-state"><Icon name="check"/><strong>{title}</strong><p>{detail}</p></div>;}
function SourceLinks({sources}){return <div className="react-source-links">{list(sources).map((s,i)=>safeURL(s.url||s.source_url)?<a key={i} href={safeURL(s.url||s.source_url)} target="_blank" rel="noopener noreferrer">{s.title||s.locator||'공식 근거'} <Icon name="arrow"/></a>:null)}</div>;}

export function CaseAutomation({caseData:c}){
  const intake=c?.intake,pendingConsultation=intake&&['received','consultation_requested'].includes(intake.status);
  if(pendingConsultation)return <section className="card case-automation" aria-label="세부 상담 진행" data-react-component="CaseAutomation"><div className="automation-heading"><div><div className="eyebrow">CONSULTATION FIRST</div><h2>{intake.status==='received'?'상담 신청을 확인해 주세요.':'세부 상담 기록을 작성해 주세요.'}</h2><p>고객의 신청을 확인하고 세부 상담을 완료하면, 담당자가 기록한 내용에서 추출합니다.</p></div><Button tab="consultation">{intake.status==='received'?'신청 확인·상담 요청':'상담 기록 작성'} <Icon name="arrow"/></Button></div><div className="automation-current"><div className="automation-status-symbol"><Icon name="message"/></div><div><span className="automation-now">현재 진행 단계</span><h3>{intake.status==='received'?'상담 신청 접수':'세부 상담 진행 중'}</h3><p>{intake.status==='received'?'고객에게 확인할 내용을 정리해 세부 상담을 요청하세요.':'고객 답변과 전화·대면 상담 내용을 상담 기록에 정리해 주세요.'}</p></div></div><ol className="ax-pipeline react-pipeline">{[['상담 신청 접수','고객이 남긴 신청 원문 확인'],['세부 상담','담당자 요청·상담 내용 기록'],['상담 내용 추출','상담 완료 후 필요한 서류 선정']].map(([title,detail],index)=><li key={title} className={index===0?'done':index===1&&intake.status==='consultation_requested'?'current':''}><span>{index===0?<Icon name="check"/>:index+1}</span><strong>{title}</strong><small>{detail}</small></li>)}</ol><div className="automation-next"><Icon name="info"/><p>신청 본문만으로 분석하거나 서류를 요청하지 않습니다. 세부 상담 완료 후 추출·서류 요청·제출 검증으로 이어지며, 이미 받은 자료는 보관합니다.</p></div></section>;
  const p=c?.ax_pipeline;if(!p)return null;
  const steps=list(p.steps),done=steps.filter(s=>s.status==='completed').length;
  const stageStep=({human_review:'human_review',submission_ready:'submission',submitted:'submission'})[p.stage];
  const current=steps.find(s=>s.id===stageStep)||steps.find(s=>s.status==='running')||steps.find(s=>['blocked','failed','review_required'].includes(s.status))||steps.find(s=>s.status!=='completed');
  const queued=p.queued_update?.status==='queued',running=p.active_run?.status==='running'||p.status==='running';
  const progress=p.progress,total=Number(progress?.total),completed=Math.max(0,Math.min(total,Number(progress?.completed)));
  const hasProgress=Boolean(progress&&Number.isFinite(total)&&total>0&&Number.isFinite(completed));
  const reasons=list(p.reasons||c.legal_analysis?.reasons),strategies=list(p.strategies||c.legal_analysis?.strategies);
  const triggerNames={manual:'담당자 확인 요청',document_uploaded:'새 서류 수신',document_received:'새 서류 수신',client_message:'고객 답변 수신',intake:'상담 내용 접수',legal_update:'적용 법률 변경'};
  const checkNames={document_selection:'서류 선정·범위 검증',ocr:'추출값 원문 검증',calculation_mapping:'계산 입력값 검증',document:'작성 문서 검증',artifact:'출력 파일 검증'};
  const stageTitles=Object.fromEntries(steps.map(step=>[step.id,step.title]));
  const checkpoints=list(c.workflow_checkpoints).map((entry,index)=>({...entry,id:`checkpoint-${index}`,checkpoint:true,title:stageTitles[entry.current_step]||stageNames[entry.stage]||'진행 조건 확인',description:`${stepNames[entry.status]||'상태 확인'}${entry.input_revision?' · 자료 '+entry.input_revision+'차':''} · ${list(entry.completed_steps).length}단계 완료`}));
  const history=[...checkpoints,...list(p.history),...list(c.ax_pipeline_history),...list(c.automation_history),...list(c.verification_runs).map(run=>({id:run.id,at:run.created_at,title:checkNames[run.kind]||'자료 검증',description:run.passed?'근거 대조를 완료했습니다.':run.status==='unavailable'?'검증 연결을 확인한 뒤 다시 진행합니다.':'대조 결과에 추가 확인이 필요합니다.'})),...list(c.strategy_analyses).map(run=>({id:run.id,at:run.created_at,title:'법률 쟁점·전략 확인',description:run.verification?.passed?'계산과 적용 근거를 함께 확인했습니다.':'적용 근거와 대응안의 검토가 필요합니다.'}))].filter((h,i,all)=>all.findIndex(x=>(x.id||x.run_id||'')===(h.id||h.run_id||'')&&(x.at||x.created_at)===(h.at||h.created_at)&&(x.stage||x.title||x.trigger)===(h.stage||h.title||h.trigger))===i).sort((a,b)=>String(a.at||a.created_at||'').localeCompare(String(b.at||b.created_at||'')));
  const percent=steps.length?Math.round(done/steps.length*100):0;
  const documentPhase=['drafting','document_verification','human_review','submission_ready','submitted','completed'].includes(p.stage);
  const nextMessage=p.stage==='submitted'?'실제 제출 후 등록한 접수증과 사건번호를 문서·결과에서 확인할 수 있습니다.':p.stage==='submission_ready'?'승인된 제출 패키지가 준비되었습니다. 전자소송에 직접 제출한 뒤 접수증과 법원 사건번호를 등록하세요.':p.stage==='verification_waiting'?'서류별 추출과 전체 원문 대조가 아직 끝나지 않았습니다. 완료 전에는 계산과 새 문서를 생성하지 않습니다. 받은 서류의 진행 상태를 확인하고, 처리 문제가 해결되면 ‘다시 확인’으로 재검증하세요. 기존 추출값과 작성 이력은 보존됩니다.':p.stage==='human_review'||p.stage==='completed'?'1차 작성본과 AI 검토 결과를 확인하세요. 미확정 항목을 보완하고 다시 검토한 후 변호사가 최종 제출 패키지를 승인합니다.':p.stage==='lawyer_review'?'검토가 필요한 사유를 아래에 모았습니다. 판단을 기록하거나 자료를 보완하면 쟁점과 계산을 다시 확인합니다.':'필요한 서류의 추출·검토와 전체 원문 대조가 끝나면 쟁점·계산, 1차 문서 작성과 AI 검토까지 자동으로 진행합니다. 담당자는 작성본을 보완·승인하고 실제 제출을 처리합니다.';
  return <section className="card case-automation" aria-label="사건 자동 진행" data-react-component="CaseAutomation">
    <div className="automation-heading"><div><div className="eyebrow">CASE AUTOMATION</div><h2>사건의 다음 단계를 연결합니다.</h2><p>서류 준비부터 1차 작성·검토·최종 승인·제출 기록까지 모든 과정을 확인합니다.</p></div><Button secondary action="automation-run" disabled={running||queued||p.status==='queued'}><Icon name="refresh"/> 다시 확인</Button></div>
    <div className="automation-current" aria-live="polite"><div className={`automation-status-symbol ${running?'is-running':''}`}><Icon name={p.stage==='lawyer_review'?'scale':p.status==='completed'?'check':'spark'}/></div><div><span className="automation-now">{running?'현재 진행 중':p.status==='queued'?'실행 순서 대기':'현재 진행 단계'}</span><h3>{p.status==='queued'&&!running?'자동 검증 순서를 기다리고 있습니다.':stageNames[p.stage]||p.label||current?.title||'진행 상태 확인'}</h3><p>{p.status==='queued'&&!running?'확인할 작업이 대기 중입니다. 시작되면 단계별 진행 상황을 표시합니다.':(current?.detail||p.summary)?explanation(current?.detail||p.summary):'현재 자료와 근거를 확인하고 다음 단계를 준비합니다.'}</p></div><div className="automation-completion"><strong>{done}<span> / {steps.length}</span></strong><small>단계 완료</small></div></div>
    {hasProgress&&<div className="automation-work-progress" aria-live="polite"><div><strong>{explanation(progress.label)||'서류 확인 진행'}</strong><span>{completed} / {total}건 확인</span></div><progress value={completed} max={total} aria-label={explanation(progress.label)||'서류 확인 진행'}/></div>}
    {queued&&<div className="automation-queue-notice" role="status"><Icon name="clock"/><div><strong>{running?'최신 자료 반영 대기':'자동 검증 대기'}</strong><p>{running?'현재 자료를 검증하고 있습니다. 새로 변경된 자료는 이어지는 검토에 반영합니다.':'작업 순서가 되면 제출된 자료의 확인을 시작합니다. 진행 상황은 자동으로 갱신됩니다.'}</p></div></div>}
    <div className="automation-progress" role="progressbar" aria-valuemin={0} aria-valuemax={100} aria-valuenow={percent} aria-label="사건 처리 단계"><span style={{width:`${percent}%`}}/></div>
    <ol className="ax-pipeline react-pipeline">{steps.map((step,i)=><li key={step.id||i} className={step.status==='completed'?'done':step.status==='running'?'current':['blocked','review_required','failed'].includes(step.status)?'blocked':''}><span>{step.status==='completed'?<Icon name="check"/>:i+1}</span><strong>{step.title||step.label||'진행 단계'}</strong><small>{stepNames[step.status]||'대기'}</small>{step.detail&&<p>{step.detail}</p>}</li>)}</ol>
    <div className="automation-next"><Icon name="info"/><div><p>{nextMessage}</p>{documentPhase&&<div className="row wrap" style={{marginTop:12}}><Button secondary tab="court_forms"><Icon name="file"/>작성본·AI 검토 확인</Button><Button tab="bundles">{p.stage==='submitted'?'제출 기록 확인':p.stage==='submission_ready'?'접수증 등록·제출 기록':'보완·승인 및 제출 준비'} <Icon name="arrow"/></Button></div>}</div></div>
    <ApprovalEstimate caseData={c}/>
    {(reasons.length>0||strategies.length>0)&&<div className="automation-review-grid">{[[reasons,'검토가 필요한 이유'],[strategies,'근거에 따른 대응안']].map(([items,title])=>items.length>0&&<section key={title}><h3>{title}</h3>{items.map((item,i)=><article key={i}><strong>{readableText(calculationBlockerTitle(item))}</strong><p>{explanation(item)}</p>{list(item.actions).length>0&&<ul>{item.actions.map((a,i)=><li key={i}>{explanation(a)}</li>)}</ul>}{list(item.required_evidence).length>0&&<p>추가 근거 · {item.required_evidence.map(explanation).join(" · ")}</p>}<SourceLinks sources={item.sources||item.source_refs}/></article>)}</section>)}</div>}
    <details className="automation-history"><summary>단계별 이력과 처리 근거 <span>{history.length}건</span></summary>{current?.gate&&<div className="automation-current-gate"><strong>다음 단계로 진행하는 조건</strong><p>{current.gate}</p>{current.on_failure&&<small>조건이 충족되지 않으면 · {current.on_failure}</small>}</div>}<div className="automation-stage-contracts">{steps.filter(step=>step.gate||list(step.inputs).length||list(step.outputs).length).map((step,index)=><details key={step.id||index}><summary>{step.title} <span>{stepNames[step.status]||'대기'}</span></summary><dl><dt>확인 자료</dt><dd>{list(step.inputs).join(' · ')||'현재 사건 자료'}</dd><dt>처리 결과</dt><dd>{list(step.outputs).join(' · ')||'확인 중'}</dd><dt>진행 조건</dt><dd>{step.gate||'근거 확인'}</dd><dt>보완 방법</dt><dd>{step.on_failure||'담당자 확인'}</dd></dl></details>)}</div>{history.length?history.slice().reverse().map((h,i)=><div className="timeline-row" key={`${h.id||h.run_id||'event'}:${i}`}><span className="timeline-dot"/><div><strong>{stageNames[h.stage]||h.title||'진행 상태 변경'}</strong><p>{date(h.at||h.created_at,true)} · {h.reason||h.description||triggerNames[h.trigger]||'처리 상태를 기록했습니다.'}</p>{h.checkpoint&&h.gate&&<p>진행 조건 · {h.gate}</p>}{h.checkpoint&&list(h.completed_steps).length>0&&<p>확인 완료 · {h.completed_steps.map(id=>stageTitles[id]).filter(Boolean).join(' · ')||list(h.completed_steps).length+'단계'}</p>}</div></div>):<p className="small muted">현재 처리 상태가 위 단계에 표시됩니다. 다음 상태 변경부터 이력을 함께 확인할 수 있습니다.</p>}</details>
    {p.legal_update&&<div className="automation-legal-basis"><Icon name="scale"/><div><strong>적용 법률 기준</strong><p>{legalBasisLabel(p.legal_update)}</p>{p.legal_update.summary&&<p>{explanation(p.legal_update.summary)}</p>}</div><button className="button subtle small" data-nav="knowledge">변경 이력</button></div>}
    {p.updated_at&&<p className="automation-updated">최근 확인 {date(p.updated_at,true)}</p>}
  </section>;
}

function OfficeShell({state,user,currentName,contentHtml,alarmHtml,roleLabel,api}){
  const navs=[['cases','folder','전체 사건'],...(state.current?[['case','grid','선택한 사건']]:[]),['agent','spark','검토 작업실']];
  const nav=(id,i,title)=><button key={id} className={`nav-link ${state.view===id?'active':''}`} data-nav={id}><Icon name={i}/>{title}{id==='cases'&&<span className="nav-count">{state.total||state.cases.length}</span>}</button>;
  return <div className="office-shell premium-office" data-react-component="OfficeShell"><aside className="sidebar"><div className="brand"><Html html={brand()}/></div><div className="workspace-chip"><span className="dot"/>개인회생 업무공간</div><div className="nav-heading">WORKSPACE</div>{navs.map(n=>nav(...n))}<div className="nav-heading">RESOURCES</div>{[['knowledge','search','수집 지식함'],['registry','building','법원·발급처'],['system','shield','운영 현황']].map(n=>nav(...n))}<div className="sidebar-reassurance"><span>CLARITY. CARE. PROGRESS.</span><p>판단에 집중하고,<br/>과정은 빈틈없이.</p></div><div className="sidebar-bottom"><div className="privacy-line"><Icon name="shield"/>사건별 권한 · 변경 이력 기록</div></div></aside><div className="office-main"><header className="topbar"><button className="icon-button mobile-menu" data-action="menu" aria-label="메뉴 열기"><Icon name="menu"/></button><div className="breadcrumb">업무공간 <Icon name="chevron"/><strong>{currentName}</strong></div><div className="spacer"/><span className="today">{new Intl.DateTimeFormat('ko-KR',{timeZone:'Asia/Seoul',month:'long',day:'numeric',weekday:'short'}).format(new Date())}</span><span className="topbar-divider"/><Html html={alarmHtml}/><span className="avatar">{user.name?.slice(0,1)}</span><div className="user-meta">{user.name}<small>{roleLabel}</small></div><button className="icon-button" data-action="logout" aria-label="로그아웃"><Icon name="logout"/></button></header><main className="content" id="page-content">{["knowledge","system"].includes(state.view)&&<LegalUpdates request={api} role={user.role}/>}<div className="legacy-case-views" dangerouslySetInnerHTML={{__html:contentHtml}}/></main></div></div>;
}

function rootFor(node){if(!roots.has(node))roots.set(node,createRoot(node));return roots.get(node);}
export function clearWorkspace(){pipelineRoots.forEach(r=>r.unmount());pipelineRoots=[];for(const root of roots.values())root.unmount();roots.clear();}
export function renderOffice(props){
  pipelineRoots.forEach(r=>r.unmount());pipelineRoots=[];
  flushSync(()=>rootFor(document.querySelector('#app')).render(<OfficeShell {...props}/>));
  document.querySelectorAll('[data-case-automation]').forEach(node=>{const root=createRoot(node);pipelineRoots.push(root);flushSync(()=>root.render(<CaseAutomation caseData={props.state.current}/>));});
}
